def n(node_id, kind, en, zh):
    return {"id": node_id, "kind": kind, "en": en, "zh": zh}


def e(src, dst, label_en=None, label_zh=None, style="solid"):
    return {
        "src": src,
        "dst": dst,
        "label_en": label_en,
        "label_zh": label_zh,
        "style": style,
    }


def spec(nodes, edges, decisions_en, decisions_zh, hotspots_en, hotspots_zh):
    return {
        "nodes": nodes,
        "edges": edges,
        "decisions_en": decisions_en,
        "decisions_zh": decisions_zh,
        "hotspots_en": hotspots_en,
        "hotspots_zh": hotspots_zh,
    }


VISUALS = {
    "AgentTool": spec(
        nodes=[
            n("A", "start", "Start", "开始"),
            n("B", "step", "Parse input", "解析输入"),
            n("C", "step", "Resolve team or named-agent context", "解析 team 或命名 agent 上下文"),
            n("D", "decision", "team_name + name set?", "team_name 和 name 是否同时存在？"),
            n("E", "step", "Spawn teammate path", "进入 teammate 创建路径"),
            n("F", "step", "Resolve fork or named agent", "解析 fork 或命名 agent"),
            n("G", "decision", "Permissions / MCP / isolation OK?", "权限 / MCP / 隔离是否通过？"),
            n("H", "step", "Apply cwd / worktree / remote mode", "应用 cwd / worktree / remote 模式"),
            n("I", "decision", "Run in background?", "是否后台运行？"),
            n("J", "step", "Launch background session", "启动后台会话"),
            n("K", "step", "Run agent now", "立即运行 agent"),
            n("L", "result", "Return result or agentId", "返回结果或 agentId"),
            n("X1", "gap", "Original also covers real swarm / remote lifecycle", "原版还覆盖真实 swarm / remote 生命周期"),
            n("X2", "gap", "Go ignores team_name / mode / isolation / subagent_type at runtime", "Go 运行时忽略 team_name / mode / isolation / subagent_type"),
        ],
        edges=[
            e("A", "B"),
            e("B", "C"),
            e("C", "D"),
            e("D", "E", "Yes", "是"),
            e("D", "F", "No", "否"),
            e("E", "G"),
            e("F", "G"),
            e("G", "L", "No", "否"),
            e("G", "H", "Yes", "是"),
            e("H", "I"),
            e("I", "J", "Yes", "是"),
            e("I", "K", "No", "否"),
            e("J", "L"),
            e("K", "L"),
            e("C", "X2", style="note"),
            e("H", "X1", style="note"),
        ],
        decisions_en=[
            "`team_name + name set?` decides whether the call should become a swarm teammate spawn or a normal delegated agent run.",
            "`Permissions / MCP / isolation OK?` is where the original validates execution policy, required MCP servers, and isolation mode before any sub-agent runs.",
            "`Run in background?` splits the synchronous result path from the retained background-session path.",
        ],
        decisions_zh=[
            "`team_name 和 name 是否同时存在？` 决定这次调用走 swarm teammate 创建，还是普通委派 agent 运行。",
            "`权限 / MCP / 隔离是否通过？` 是原版在任何子 agent 真正运行前做执行策略、所需 MCP 服务和隔离模式校验的位置。",
            "`是否后台运行？` 把同步返回路径和保留后台会话的路径分开。",
        ],
        hotspots_en=[
            "At context resolution, the original can spawn teammates, resolve named definitions, and prepare remote-capable execution; Go mostly stays in a local QueryLoop model.",
            "At validation, the original has explicit MCP / permission / isolation gates; Go parses several fields but does not drive behavior from them.",
            "At lifecycle handling, the original keeps richer transcript and swarm state; Go background continuation is still in-memory session retention.",
        ],
        hotspots_zh=[
            "在上下文解析阶段，原版可以创建 teammate、解析命名定义，并准备 remote-capable 执行；Go 主要仍停留在本地 QueryLoop 模型里。",
            "在校验阶段，原版有明确的 MCP / 权限 / 隔离 gate；Go 会解析若干字段，但不会据此驱动行为。",
            "在生命周期处理阶段，原版维护更丰富的 transcript 和 swarm 状态；Go 的后台续跑仍是进程内会话保留。",
        ],
    ),
    "AskUserQuestionTool": spec(
        nodes=[
            n("A", "start", "Start", "开始"),
            n("B", "step", "Parse question set", "解析问题集合"),
            n("C", "decision", "Question schema valid?", "问题结构是否有效？"),
            n("D", "result", "Return validation error", "返回校验错误"),
            n("E", "step", "Render questionnaire", "渲染问卷"),
            n("F", "step", "Collect user choice(s)", "收集用户选择"),
            n("G", "decision", "Answer valid?", "答案是否有效？"),
            n("H", "step", "Normalize answer payload", "规范化答案载荷"),
            n("I", "result", "Return answers", "返回答案"),
            n("X1", "gap", "Original feeds a typed result back into runtime state", "原版会把 typed result 回送运行时状态"),
            n("X2", "gap", "Go returns the same payload as JSON text", "Go 把同样载荷作为 JSON 文本返回"),
        ],
        edges=[
            e("A", "B"),
            e("B", "C"),
            e("C", "D", "No", "否"),
            e("C", "E", "Yes", "是"),
            e("E", "F"),
            e("F", "G"),
            e("G", "F", "No", "否"),
            e("G", "H", "Yes", "是"),
            e("H", "I"),
            e("H", "X1", style="note"),
            e("H", "X2", style="note"),
        ],
        decisions_en=[
            "`Question schema valid?` covers missing headers, bad option lists, and malformed multi-select configuration.",
            "`Answer valid?` decides whether the UI must keep waiting or can hand control back to the model with a constrained answer payload.",
        ],
        decisions_zh=[
            "`问题结构是否有效？` 覆盖了缺失 header、错误的选项列表，以及畸形的多选配置。",
            "`答案是否有效？` 决定 UI 是否必须继续等待，还是可以把受约束的答案载荷交还给模型。",
        ],
        hotspots_en=[
            "The shared path is straightforward: validate, present, collect, and normalize.",
            "The main parity gap is after collection: the original returns a richer typed runtime object, while Go serializes the result as JSON text.",
        ],
        hotspots_zh=[
            "共享路径本身比较直接：校验、展示、收集、规范化。",
            "主要一致性差距出现在收集之后：原版返回更丰富的 typed runtime 对象，而 Go 会把结果序列化成 JSON 文本。",
        ],
    ),
    "BashTool": spec(
        nodes=[
            n("A", "start", "Start", "开始"),
            n("B", "step", "Plan-mode check", "Plan 模式检查"),
            n("C", "step", "Parse input", "解析输入"),
            n("D", "decision", "Command empty?", "命令是否为空？"),
            n("E", "result", "Return usage-style fallback", "返回用法式兜底结果"),
            n("F", "decision", "sleep >= 2 without background?", "是否存在未后台化的 sleep >= 2？"),
            n("G", "result", "Return background guidance", "返回后台执行指导"),
            n("H", "decision", "Dangerous command blocked?", "危险命令是否被拦截？"),
            n("I", "step", "Normalize timeout", "规范化超时"),
            n("J", "decision", "Run in background?", "是否后台运行？"),
            n("K", "step", "Launch background task", "启动后台任务"),
            n("L", "step", "Build sandboxed command", "构造沙箱命令"),
            n("M", "step", "Run command and capture output", "执行命令并捕获输出"),
            n("N", "decision", "Timed out or failed?", "是否超时或失败？"),
            n("O", "result", "Format error-style shell result", "格式化错误式 shell 结果"),
            n("P", "result", "Format success shell result", "格式化成功 shell 结果"),
            n("X1", "gap", "Original runs deeper hook + permission + shell analysis first", "原版会先跑更深的 hook + 权限 + shell 分析"),
            n("X2", "gap", "Original can stream progress and auto-background long runs", "原版可以流式汇报进度并自动后台化长任务"),
            n("X3", "gap", "Original also simulates sed edits and persists large output", "原版还会模拟 sed 编辑并持久化大输出"),
        ],
        edges=[
            e("A", "B"),
            e("B", "C"),
            e("C", "D"),
            e("D", "E", "Yes", "是"),
            e("D", "F", "No", "否"),
            e("F", "G", "Yes", "是"),
            e("F", "H", "No", "否"),
            e("H", "O", "Yes", "是"),
            e("H", "I", "No", "否"),
            e("I", "J"),
            e("J", "K", "Yes", "是"),
            e("J", "L", "No", "否"),
            e("K", "P"),
            e("L", "M"),
            e("M", "N"),
            e("N", "O", "Yes", "是"),
            e("N", "P", "No", "否"),
            e("B", "X1", style="note"),
            e("J", "X2", style="note"),
            e("M", "X3", style="note"),
        ],
        decisions_en=[
            "`Command empty?` decides whether the tool stops immediately with a usage-style fallback.",
            "`sleep >= 2 without background?` captures the explicit guard that blocks obvious long waits in the foreground path.",
            "`Dangerous command blocked?` is the short Go-side safety gate before execution begins.",
            "`Run in background?` splits immediate execution from task launch.",
            "`Timed out or failed?` determines whether the tool emits an error-style shell result or a normal success response.",
        ],
        decisions_zh=[
            "`命令是否为空？` 决定工具是否立刻停下并返回用法式兜底结果。",
            "`是否存在未后台化的 sleep >= 2？` 对应的是显式前置保护：阻断明显需要长时间等待的前台路径。",
            "`危险命令是否被拦截？` 是 Go 侧在执行前的短链路安全 gate。",
            "`是否后台运行？` 把立即执行和任务启动分成两条路径。",
            "`是否超时或失败？` 决定工具最终返回错误式 shell 结果，还是正常成功响应。",
        ],
        hotspots_en=[
            "Before execution, the original runs a much deeper permission and hook pipeline, including AST-style shell analysis and richer allow / ask / deny logic.",
            "Around execution, the original can stream progress, auto-background commands, and handle simulated edit semantics; Go mainly chooses between immediate run and explicit background launch.",
            "After execution, the original keeps richer task-aware output handling, including large-output persistence and image / hint post-processing.",
        ],
        hotspots_zh=[
            "在执行前，原版会跑一条更深的权限与 hook 流水线，包括接近 AST 级的 shell 分析，以及更丰富的 allow / ask / deny 逻辑。",
            "在执行过程中，原版可以流式汇报进度、自动后台化命令，并处理模拟编辑语义；Go 主要只是在立即执行和显式后台启动之间二选一。",
            "在执行后，原版保留了更丰富的任务感知输出处理，包括大输出持久化，以及图片 / hint 的后处理。",
        ],
    ),
    "BriefTool": spec(
        nodes=[
            n("A", "start", "Start", "开始"),
            n("B", "step", "Parse message, status, attachments", "解析 message、status 和 attachments"),
            n("C", "decision", "Payload valid?", "载荷是否有效？"),
            n("D", "result", "Return validation error", "返回校验错误"),
            n("E", "step", "Normalize brief user-facing payload", "规范化简短用户消息载荷"),
            n("F", "step", "Send brief message to UI / CLI", "把简短消息发送到 UI / CLI"),
            n("G", "result", "Return acknowledgement", "返回确认结果"),
            n("X1", "gap", "Original treats this as a richer UI event channel", "原版把它作为更丰富的 UI 事件通道"),
            n("X2", "gap", "Go mostly forwards plain text with light metadata", "Go 主要是带少量元数据的纯文本透传"),
        ],
        edges=[
            e("A", "B"),
            e("B", "C"),
            e("C", "D", "No", "否"),
            e("C", "E", "Yes", "是"),
            e("E", "F"),
            e("F", "G"),
            e("E", "X1", style="note"),
            e("F", "X2", style="note"),
        ],
        decisions_en=[
            "`Payload valid?` covers whether the tool received a coherent message body and optional presentation metadata.",
        ],
        decisions_zh=[
            "`载荷是否有效？` 覆盖的是工具是否收到了一致的消息体，以及可选的展示元数据。",
        ],
        hotspots_en=[
            "The shared flow is short: validate, normalize, send, acknowledge.",
            "The main difference is conceptual: the original models a richer UI event, while Go still behaves like a lightweight message passthrough.",
        ],
        hotspots_zh=[
            "共享流程本身很短：校验、规范化、发送、确认。",
            "主要差异是概念层面的：原版把它建模为更丰富的 UI 事件，而 Go 仍更像轻量消息透传。",
        ],
    ),
    "CronCreateTool": spec(
        nodes=[
            n("A", "start", "Start", "开始"),
            n("B", "step", "Parse cron job request", "解析 cron 任务请求"),
            n("C", "decision", "Cron expression valid?", "Cron 表达式是否有效？"),
            n("D", "result", "Return validation error", "返回校验错误"),
            n("E", "step", "Build durable job record", "构造可持久化任务记录"),
            n("F", "step", "Persist cron job", "持久化 cron 任务"),
            n("G", "step", "Schedule next firing", "安排下一次触发"),
            n("H", "result", "Return job id and summary", "返回任务 id 和摘要"),
            n("X1", "gap", "Original runtime reconnects firing back into a richer main loop", "原版运行时会把触发结果更完整地接回主循环"),
        ],
        edges=[
            e("A", "B"),
            e("B", "C"),
            e("C", "D", "No", "否"),
            e("C", "E", "Yes", "是"),
            e("E", "F"),
            e("F", "G"),
            e("G", "H"),
            e("G", "X1", style="note"),
        ],
        decisions_en=[
            "`Cron expression valid?` decides whether the runtime can safely persist and schedule the job at all.",
        ],
        decisions_zh=[
            "`Cron 表达式是否有效？` 决定运行时能否安全地持久化并调度这个任务。",
        ],
        hotspots_en=[
            "The shared path persists and schedules the job similarly.",
            "The bigger divergence starts after creation: the original firing lifecycle is still richer than the Go runtime.",
        ],
        hotspots_zh=[
            "共享路径在持久化和调度这一步上是相近的。",
            "更大的分歧发生在创建之后：原版的触发生命周期仍比 Go 运行时更丰富。",
        ],
    ),
    "CronDeleteTool": spec(
        nodes=[
            n("A", "start", "Start", "开始"),
            n("B", "step", "Parse job id", "解析任务 id"),
            n("C", "decision", "Job exists?", "任务是否存在？"),
            n("D", "result", "Return not-found result", "返回未找到结果"),
            n("E", "step", "Unschedule job", "取消调度任务"),
            n("F", "step", "Remove persisted record", "删除持久化记录"),
            n("G", "result", "Return deletion summary", "返回删除摘要"),
            n("X1", "gap", "Original deletion sits inside a richer cron lifecycle", "原版删除动作位于更完整的 cron 生命周期中"),
        ],
        edges=[
            e("A", "B"),
            e("B", "C"),
            e("C", "D", "No", "否"),
            e("C", "E", "Yes", "是"),
            e("E", "F"),
            e("F", "G"),
            e("E", "X1", style="note"),
        ],
        decisions_en=[
            "`Job exists?` determines whether the runtime can actually unschedule a live cron entry or only report a no-op / not-found result.",
        ],
        decisions_zh=[
            "`任务是否存在？` 决定运行时是真正取消一个已存在的 cron 条目，还是只返回 no-op / not-found 结果。",
        ],
        hotspots_en=[
            "Delete itself is close between the two implementations.",
            "The remaining difference is mostly in the richer original cron lifecycle around scheduling and firing, not in the delete operation itself.",
        ],
        hotspots_zh=[
            "删除动作本身在两边之间已经比较接近。",
            "剩余差异主要在原版更完整的 cron 调度和触发生命周期，而不是 delete 操作本身。",
        ],
    ),
    "CronListTool": spec(
        nodes=[
            n("A", "start", "Start", "开始"),
            n("B", "step", "Load persisted cron jobs", "加载持久化 cron 任务"),
            n("C", "decision", "Any jobs?", "是否存在任务？"),
            n("D", "result", "Return empty-state result", "返回空状态结果"),
            n("E", "step", "Sort and format jobs", "排序并格式化任务"),
            n("F", "result", "Return cron list", "返回 cron 列表"),
            n("X1", "gap", "Original list output sits on top of a richer cron runtime", "原版列表输出建立在更完整的 cron 运行时之上"),
        ],
        edges=[
            e("A", "B"),
            e("B", "C"),
            e("C", "D", "No", "否"),
            e("C", "E", "Yes", "是"),
            e("E", "F"),
            e("E", "X1", style="note"),
        ],
        decisions_en=[
            "`Any jobs?` decides whether the tool returns a meaningful schedule listing or an explicit empty-state response.",
        ],
        decisions_zh=[
            "`是否存在任务？` 决定工具是返回一份有内容的调度列表，还是显式的空状态响应。",
        ],
        hotspots_en=[
            "The list path itself is direct: load, sort, format, return.",
            "As with the other cron tools, the bigger remaining difference is in the runtime behind the list rather than in listing itself.",
        ],
        hotspots_zh=[
            "列表路径本身比较直接：加载、排序、格式化、返回。",
            "和其他 cron 工具一样，真正更大的剩余差异在列表背后的运行时，而不是 list 这个动作本身。",
        ],
    ),
    "EnterPlanModeTool": spec(
        nodes=[
            n("A", "start", "Start", "开始"),
            n("B", "decision", "Entry allowed in this context?", "当前上下文是否允许进入？"),
            n("C", "result", "Return rejection", "返回拒绝结果"),
            n("D", "step", "Record plan-mode transition", "记录 plan-mode 切换"),
            n("E", "step", "Switch permission mode to plan", "把权限模式切到 plan"),
            n("F", "result", "Return planning instructions", "返回规划指引"),
            n("X1", "gap", "Go also creates a timestamped plan file immediately", "Go 还会立刻创建带时间戳的计划文件"),
            n("X2", "gap", "Original relies more on AppState permission orchestration", "原版更依赖 AppState 层的权限编排"),
        ],
        edges=[
            e("A", "B"),
            e("B", "C", "No", "否"),
            e("B", "D", "Yes", "是"),
            e("D", "E"),
            e("E", "F"),
            e("D", "X1", style="note"),
            e("E", "X2", style="note"),
        ],
        decisions_en=[
            "`Entry allowed in this context?` captures the channels / agent-context checks that decide whether plan mode can be entered at all.",
        ],
        decisions_zh=[
            "`当前上下文是否允许进入？` 对应的是 channels / agent-context 检查，用来决定 plan mode 是否能被进入。",
        ],
        hotspots_en=[
            "Both versions explicitly enter a planning state before implementation continues.",
            "The original treats the mode switch mainly as permission-state orchestration; Go additionally materializes a plan file and later enforces writes through PlanState checks.",
        ],
        hotspots_zh=[
            "两边都会在继续实现前显式进入一个规划状态。",
            "原版主要把这次切换当作权限状态编排；Go 额外会落地生成计划文件，并在后续通过 PlanState 检查拦写。",
        ],
    ),
    "EnterWorktreeTool": spec(
        nodes=[
            n("A", "start", "Start", "开始"),
            n("B", "decision", "Already in active worktree session?", "是否已经处于激活的 worktree 会话？"),
            n("C", "result", "Return rejection", "返回拒绝结果"),
            n("D", "step", "Resolve main repo root", "解析主仓库根目录"),
            n("E", "decision", "Valid worktree name / slug?", "worktree 名称 / slug 是否有效？"),
            n("F", "step", "Create or resume worktree", "创建或恢复 worktree"),
            n("G", "step", "Switch session into worktree", "把会话切入 worktree"),
            n("H", "step", "Persist worktree session state", "持久化 worktree 会话状态"),
            n("I", "result", "Return worktree path and branch", "返回 worktree 路径和分支"),
            n("X1", "gap", "Go does not canonicalize to the main repo root like the original", "Go 不会像原版那样规范化到主仓库根目录"),
            n("X2", "gap", "Go does not persist or restore session worktree state", "Go 不会持久化或恢复会话级 worktree 状态"),
        ],
        edges=[
            e("A", "B"),
            e("B", "C", "Yes", "是"),
            e("B", "D", "No", "否"),
            e("D", "E"),
            e("E", "C", "No", "否"),
            e("E", "F", "Yes", "是"),
            e("F", "G"),
            e("G", "H"),
            e("H", "I"),
            e("D", "X1", style="note"),
            e("H", "X2", style="note"),
        ],
        decisions_en=[
            "`Already in active worktree session?` prevents nesting incompatible worktree transitions.",
            "`Valid worktree name / slug?` is where the original enforces naming and reuse rules before any git operation happens.",
        ],
        decisions_zh=[
            "`是否已经处于激活的 worktree 会话？` 用来阻止不兼容的嵌套 worktree 切换。",
            "`worktree 名称 / slug 是否有效？` 是原版在任何 git 操作发生前执行命名和复用规则校验的位置。",
        ],
        hotspots_en=[
            "The original canonically resolves the main repo root and can resume named worktrees; Go mostly creates a fresh `.claude/worktrees/...` entry under the current repo.",
            "The original also persists and later restores session worktree state; Go keeps much lighter in-memory state.",
        ],
        hotspots_zh=[
            "原版会规范化解析主仓库根目录，并且可以恢复命名 worktree；Go 主要是在当前仓库下创建新的 `.claude/worktrees/...` 条目。",
            "原版还会持久化并在之后恢复会话级 worktree 状态；Go 只保留更轻的内存态。",
        ],
    ),
    "ExitPlanModeTool": spec(
        nodes=[
            n("A", "start", "Start", "开始"),
            n("B", "decision", "Currently in plan mode?", "当前是否处于 plan mode？"),
            n("C", "result", "Return not-in-plan-mode result", "返回未处于 plan mode 的结果"),
            n("D", "step", "Load recorded plan file / content", "加载记录的计划文件 / 内容"),
            n("E", "decision", "Leader approval required?", "是否需要 leader 审批？"),
            n("F", "step", "Request approval and wait", "请求审批并等待"),
            n("G", "decision", "Approved?", "是否批准？"),
            n("H", "result", "Return rejection or stay in plan mode", "返回拒绝结果或保持在 plan mode"),
            n("I", "step", "Restore pre-plan state", "恢复进入 plan 前的状态"),
            n("J", "result", "Return approved plan output", "返回已批准的计划输出"),
            n("X1", "gap", "Go has no permission dialog or teammate approval branch", "Go 没有权限对话框或 teammate 审批分支"),
            n("X2", "gap", "Go simply exits PlanState and echoes the stored plan", "Go 只是退出 PlanState 并回显已存计划"),
        ],
        edges=[
            e("A", "B"),
            e("B", "C", "No", "否"),
            e("B", "D", "Yes", "是"),
            e("D", "E"),
            e("E", "F", "Yes", "是"),
            e("E", "I", "No", "否"),
            e("F", "G"),
            e("G", "H", "No", "否"),
            e("G", "I", "Yes", "是"),
            e("I", "J"),
            e("E", "X1", style="note"),
            e("I", "X2", style="note"),
        ],
        decisions_en=[
            "`Currently in plan mode?` decides whether this is a valid state transition or a no-op / error.",
            "`Leader approval required?` is where the original branches into teammate mailbox approval flow instead of a purely local exit.",
            "`Approved?` controls whether the runtime actually restores state and exits plan mode.",
        ],
        decisions_zh=[
            "`当前是否处于 plan mode？` 决定这是不是一个合法的状态切换，还是 no-op / error。",
            "`是否需要 leader 审批？` 是原版切入 teammate 邮箱审批流，而不是纯本地退出的地方。",
            "`是否批准？` 控制运行时是否真的恢复状态并退出 plan mode。",
        ],
        hotspots_en=[
            "The original exit flow is approval-aware and can involve team lead messaging.",
            "Go currently skips that orchestration and behaves like a local state flip plus plan-file readback.",
        ],
        hotspots_zh=[
            "原版退出流程是审批感知的，并且可能涉及 team lead 消息链路。",
            "Go 目前会跳过这层编排，更像是一次本地状态切换加计划文件回读。",
        ],
    ),
    "ExitWorktreeTool": spec(
        nodes=[
            n("A", "start", "Start", "开始"),
            n("B", "decision", "Active worktree session exists?", "是否存在激活的 worktree 会话？"),
            n("C", "result", "Return rejection", "返回拒绝结果"),
            n("D", "decision", "Keep or remove?", "保留还是移除？"),
            n("E", "step", "Restore original session state", "恢复原始会话状态"),
            n("F", "result", "Return keep summary", "返回 keep 摘要"),
            n("G", "decision", "Discard changes allowed?", "是否允许丢弃改动？"),
            n("H", "step", "Count changed files and commits", "统计变更文件和新增提交"),
            n("I", "decision", "Safe to remove?", "是否可以安全移除？"),
            n("J", "step", "Remove worktree and branch", "删除 worktree 和分支"),
            n("K", "result", "Return remove summary", "返回 remove 摘要"),
            n("X1", "gap", "Go checks file changes only; original also counts extra commits", "Go 只检查文件改动；原版还会统计额外提交"),
            n("X2", "gap", "Go never fully restores persisted worktree session state", "Go 不会完整恢复持久化的 worktree 会话状态"),
        ],
        edges=[
            e("A", "B"),
            e("B", "C", "No", "否"),
            e("B", "D", "Yes", "是"),
            e("D", "E", "Keep", "保留"),
            e("D", "G", "Remove", "移除"),
            e("E", "F"),
            e("G", "J", "Yes", "是"),
            e("G", "H", "No", "否"),
            e("H", "I"),
            e("I", "C", "No", "否"),
            e("I", "J", "Yes", "是"),
            e("J", "K"),
            e("H", "X1", style="note"),
            e("E", "X2", style="note"),
        ],
        decisions_en=[
            "`Active worktree session exists?` prevents invalid exits when the session never entered worktree mode in the first place.",
            "`Keep or remove?` selects between restoring the main session state and actually destroying the isolated git state.",
            "`Discard changes allowed?` and `Safe to remove?` are the protective gates before destructive cleanup.",
        ],
        decisions_zh=[
            "`是否存在激活的 worktree 会话？` 用来阻止从未进入 worktree 模式的会话执行非法退出。",
            "`保留还是移除？` 决定只是恢复主会话状态，还是彻底销毁隔离 git 状态。",
            "`是否允许丢弃改动？` 和 `是否可以安全移除？` 是破坏性清理前的保护 gate。",
        ],
        hotspots_en=[
            "The original remove guard is stricter: it fails closed on both changed files and extra commits, and treats unknown state as unsafe.",
            "Go never fully adopted the original persisted session restore path, so keep / remove act on lighter in-memory worktree state.",
        ],
        hotspots_zh=[
            "原版的 remove 保护更严格：它会同时对变更文件和新增提交 fail closed，并把未知状态视为不安全。",
            "Go 从未完整采纳原版那条持久化会话恢复路径，所以 keep / remove 作用的仍是更轻的内存态 worktree 状态。",
        ],
    ),
    "FileEditTool": spec(
        nodes=[
            n("A", "start", "Start", "开始"),
            n("B", "decision", "Plan mode active?", "Plan 模式是否激活？"),
            n("C", "result", "Return plan-mode rejection", "返回 plan 模式拒绝结果"),
            n("D", "step", "Parse file path and replacement strings", "解析文件路径和替换字符串"),
            n("E", "decision", "Allowed path and valid strings?", "路径允许且字符串有效吗？"),
            n("F", "result", "Return validation error", "返回校验错误"),
            n("G", "step", "Read file content", "读取文件内容"),
            n("H", "decision", "replace_all?", "是否 replace_all？"),
            n("I", "step", "Compute replacement result", "计算替换结果"),
            n("J", "decision", "Any change produced?", "是否产生改动？"),
            n("K", "result", "Return no_changes", "返回 no_changes"),
            n("L", "step", "Atomically write edited file", "原子写回编辑后的文件"),
            n("M", "result", "Return edit summary", "返回编辑摘要"),
            n("X1", "gap", "Original has richer editor-aware previews and ambiguity handling", "原版有更丰富的编辑器感知预览和歧义处理"),
        ],
        edges=[
            e("A", "B"),
            e("B", "C", "Yes", "是"),
            e("B", "D", "No", "否"),
            e("D", "E"),
            e("E", "F", "No", "否"),
            e("E", "G", "Yes", "是"),
            e("G", "H"),
            e("H", "I", "Yes / No", "是 / 否"),
            e("I", "J"),
            e("J", "K", "No", "否"),
            e("J", "L", "Yes", "是"),
            e("L", "M"),
            e("I", "X1", style="note"),
        ],
        decisions_en=[
            "`Plan mode active?` blocks edits while the session is still supposed to be planning only.",
            "`Allowed path and valid strings?` covers path policy, required fields, and the guard against identical old and new strings.",
            "`replace_all?` chooses one-shot replacement vs replace-every-match behavior.",
            "`Any change produced?` decides whether the tool writes anything or returns `no_changes`.",
        ],
        decisions_zh=[
            "`Plan 模式是否激活？` 会在会话仍应只做规划时阻断编辑。",
            "`路径允许且字符串有效吗？` 覆盖路径策略、必填字段，以及 old 和 new 相同的保护判断。",
            "`是否 replace_all？` 决定是只替换一次，还是替换全部匹配项。",
            "`是否产生改动？` 决定工具是写回文件，还是直接返回 `no_changes`。",
        ],
        hotspots_en=[
            "The Go path is intentionally simple: validate, replace, atomically write, return.",
            "The original still offers richer editor-facing instrumentation around what changed and how ambiguous matches are surfaced.",
        ],
        hotspots_zh=[
            "Go 路径是有意保持简单的：校验、替换、原子写回、返回。",
            "原版在“具体改了什么”和“如何暴露歧义匹配”这两点上仍提供了更丰富的编辑器侧支撑。",
        ],
    ),
    "FileReadTool": spec(
        nodes=[
            n("A", "start", "Start", "开始"),
            n("B", "step", "Parse file_path / offset / limit / pages", "解析 file_path / offset / limit / pages"),
            n("C", "decision", "Input and path valid?", "输入和路径是否有效？"),
            n("D", "result", "Return validation error", "返回校验错误"),
            n("E", "step", "Normalize and open file", "规范化并打开文件"),
            n("F", "decision", "Rich format branch?", "是否进入富格式分支？"),
            n("G", "step", "Notebook / image / PDF handler emits typed results", "进入 notebook / 图片 / PDF 处理器并产出 typed 结果"),
            n("H", "step", "Read text file", "读取文本文件"),
            n("I", "decision", "Read whole file or targeted range?", "读取整文件还是定向区间？"),
            n("J", "step", "Run range-aware text reader", "执行区间感知文本读取器"),
            n("K", "decision", "Selected slice exceeds byte/token caps?", "选中切片是否超过字节或 token 上限？"),
            n("L", "result", "Return numbered output", "返回带行号的结果"),
            n("M", "result", "Return bounded / rejected read", "返回受限读取或拒绝结果"),
            n("X1", "gap", "Original still does deeper path expansion and repeated-read dedup before returning content", "原版在返回内容前仍会做更深的路径扩展和重复读取去重"),
            n("X2", "gap", "Go now has targeted text-range reads plus typed notebook/image tool results", "Go 现在已有定向文本区间读取以及 typed notebook/图片 tool result"),
            n("X3", "gap", "Remaining gaps are repeated-read dedup plus deeper PDF/session behavior", "剩余差异主要是重复读取去重，以及更深的 PDF/会话行为"),
        ],
        edges=[
            e("A", "B"),
            e("B", "C"),
            e("C", "D", "No", "否"),
            e("C", "E", "Yes", "是"),
            e("E", "F"),
            e("F", "G", "Yes", "是"),
            e("F", "H", "No", "否"),
            e("H", "I"),
            e("I", "J"),
            e("J", "K"),
            e("K", "L", "No", "否"),
            e("K", "M", "Yes", "是"),
            e("G", "L"),
            e("B", "X1", style="note"),
            e("H", "X2", style="note"),
            e("G", "X3", style="note"),
        ],
        decisions_en=[
            "`Input and path valid?` covers offset / limit validation, allowed-path checks, device-file rejection, and binary-path guards.",
            "`Rich format branch?` decides whether the read is delegated to notebook / image / PDF handlers or treated as plain text.",
            "`Read whole file or targeted range?` decides whether byte caps apply to the whole file or whether a requested slice can bypass the unrestricted full-file ceiling.",
            "`Selected slice exceeds byte/token caps?` decides whether the chosen content can be returned as-is or must error after range selection.",
        ],
        decisions_zh=[
            "`输入和路径是否有效？` 覆盖 offset / limit 校验、允许路径检查、设备文件拒绝，以及二进制路径保护。",
            "`是否进入富格式分支？` 决定读取是委托给 notebook / 图片 / PDF 处理器，还是按纯文本处理。",
            "`读取整文件还是定向区间？` 决定字节上限是作用于整文件，还是在请求了区间时允许绕过整文件硬上限。",
            "`选中切片是否超过字节或 token 上限？` 决定选中的内容能否直接返回，还是要在区间选择之后报错。",
        ],
        hotspots_en=[
            "The shared path is already guard-heavy, especially around path safety and format branching.",
            "The text path is much closer now because Go also does range-aware reads before token checks and no longer injects an implicit default line cap.",
            "The notebook/image path is closer too because Go now emits typed tool results and image resize metadata instead of flattening everything into plain strings.",
            "The biggest remaining gaps are repeated-read state, deeper PDF/session-aware behavior, and some non-Anthropic transport details.",
        ],
        hotspots_zh=[
            "共享路径本身已经有很多保护，尤其在路径安全和格式分支上。",
            "文本路径现在更接近了，因为 Go 也会在 token 校验前先做区间感知读取，并且不再注入隐式默认行数上限。",
            "notebook/图片路径也更接近了，因为 Go 现在会发送 typed tool result 和图片缩放元信息，而不是把所有内容都压成纯字符串。",
            "目前最大的剩余差异主要是重复读取状态、更深的 PDF/会话感知行为，以及非 Anthropic 传输路径上的一些细节。",
        ],
    ),
    "FileWriteTool": spec(
        nodes=[
            n("A", "start", "Start", "开始"),
            n("B", "decision", "Plan mode active?", "Plan 模式是否激活？"),
            n("C", "result", "Return plan-mode rejection", "返回 plan 模式拒绝结果"),
            n("D", "step", "Parse file path and content", "解析文件路径和内容"),
            n("E", "decision", "Allowed path?", "路径是否允许？"),
            n("F", "result", "Return validation error", "返回校验错误"),
            n("G", "step", "Create parent directories if needed", "按需创建父目录"),
            n("H", "step", "Atomically write content", "原子写入内容"),
            n("I", "result", "Return success JSON", "返回成功 JSON"),
            n("X1", "gap", "Original preserves more editor and file-history semantics around writes", "原版在写入周边保留了更多编辑器和文件历史语义"),
        ],
        edges=[
            e("A", "B"),
            e("B", "C", "Yes", "是"),
            e("B", "D", "No", "否"),
            e("D", "E"),
            e("E", "F", "No", "否"),
            e("E", "G", "Yes", "是"),
            e("G", "H"),
            e("H", "I"),
            e("H", "X1", style="note"),
        ],
        decisions_en=[
            "`Plan mode active?` blocks writes while the runtime is still in read-only planning mode.",
            "`Allowed path?` is the main safety decision before any filesystem mutation happens.",
        ],
        decisions_zh=[
            "`Plan 模式是否激活？` 会在运行时仍处于只读规划模式时阻断写入。",
            "`路径是否允许？` 是任何文件系统变更发生前的主要安全判断。",
        ],
        hotspots_en=[
            "The Go path is robust but short: validate, ensure parent dirs, atomically write, return JSON.",
            "The remaining difference is mostly in the richer original tooling around editor integration and write history semantics.",
        ],
        hotspots_zh=[
            "Go 路径很稳，但很短：校验、确保父目录、原子写入、返回 JSON。",
            "剩余差异主要还是原版在编辑器集成和写入历史语义周边的更丰富能力。",
        ],
    ),
    "GlobTool": spec(
        nodes=[
            n("A", "start", "Start", "开始"),
            n("B", "step", "Parse pattern and optional path", "解析 pattern 和可选 path"),
            n("C", "decision", "Pattern and directory valid?", "pattern 和目录是否有效？"),
            n("D", "result", "Return validation error", "返回校验错误"),
            n("E", "decision", "Absolute pattern?", "是否为 absolute pattern？"),
            n("F", "step", "Extract base dir and relative glob", "提取 base dir 和相对 glob"),
            n("G", "step", "Run shared ripgrep --files search", "运行共享 ripgrep --files 搜索"),
            n("H", "step", "Relativize and cap matches", "相对化并限制结果"),
            n("I", "decision", "Any matches?", "是否有匹配？"),
            n("K", "result", "Return empty-state result", "返回空状态结果"),
            n("L", "result", "Return file list", "返回文件列表"),
            n("X1", "gap", "Original still layers permission/plugin ignore rules and richer structured metadata on top of the same discovery idea", "原版仍会在同类发现路径之上叠加权限/plugin ignore 规则和更丰富的结构化元数据"),
        ],
        edges=[
            e("A", "B"),
            e("B", "C"),
            e("C", "D", "No", "否"),
            e("C", "E", "Yes", "是"),
            e("E", "F", "Yes", "是"),
            e("E", "G", "No", "否"),
            e("F", "G"),
            e("G", "H"),
            e("H", "I"),
            e("I", "K", "No", "否"),
            e("I", "L", "Yes", "是"),
            e("H", "X1", style="note"),
        ],
        decisions_en=[
            "`Pattern and directory valid?` rejects empty patterns, missing roots, and file paths passed where a directory is required.",
            "`Absolute pattern?` decides whether the tool first extracts a static base directory before handing the relative glob to ripgrep.",
            "`Any matches?` controls empty-state output vs the final match list.",
        ],
        decisions_zh=[
            "`pattern 和目录是否有效？` 用来尽早拒绝空 pattern、缺失根目录，以及把文件路径误传成目录的情况。",
            "`是否为 absolute pattern？` 决定工具是否先提取静态 base directory，再把相对 glob 交给 ripgrep。",
            "`是否有匹配？` 决定返回空状态输出，还是最终的匹配列表。",
        ],
        hotspots_en=[
            "The core discovery path is now much closer because Go also routes globbing through a shared ripgrep-based backend.",
            "The remaining differences are mostly around permission/plugin ignore integration and richer structured runtime metadata, not the raw match engine.",
        ],
        hotspots_zh=[
            "核心发现路径现在更接近了，因为 Go 也把 glob 路由到了共享的 ripgrep 后端。",
            "剩余差异主要在权限/plugin ignore 集成和更丰富的结构化运行时元数据，而不是原始匹配引擎本身。",
        ],
    ),
    "GrepTool": spec(
        nodes=[
            n("A", "start", "Start", "开始"),
            n("B", "step", "Parse search request", "解析搜索请求"),
            n("C", "step", "Map schema aliases (-i / -C / ...)", "映射 schema 别名（-i / -C / ...）"),
            n("D", "decision", "Pattern and path valid?", "pattern 和路径是否有效？"),
            n("E", "result", "Return validation error", "返回校验错误"),
            n("F", "step", "Resolve search path and defaults", "解析搜索路径和默认值"),
            n("G", "step", "Build ripgrep flags and filters", "构建 ripgrep 标志和过滤器"),
            n("H", "step", "Run shared ripgrep backend", "运行共享 ripgrep 后端"),
            n("I", "step", "Relativize mode-specific results", "按模式相对化结果"),
            n("J", "step", "Apply offset and head_limit on result entries", "在结果条目层应用 offset 和 head_limit"),
            n("K", "decision", "Any results left?", "是否还有结果？"),
            n("L", "result", "Return grep result", "返回 grep 结果"),
            n("M", "result", "Return empty-state result", "返回空状态结果"),
            n("X1", "gap", "Original still adds permission-ignore integration, structured result metadata, and richer runtime polish around ripgrep", "原版仍会在 ripgrep 之上增加权限 ignore 集成、结构化结果元数据和更丰富的运行时细节"),
        ],
        edges=[
            e("A", "B"),
            e("B", "C"),
            e("C", "D"),
            e("D", "E", "No", "否"),
            e("D", "F", "Yes", "是"),
            e("F", "G"),
            e("G", "H"),
            e("I", "J"),
            e("H", "I"),
            e("J", "K"),
            e("K", "L", "Yes", "是"),
            e("K", "M", "No", "否"),
            e("H", "X1", style="note"),
        ],
        decisions_en=[
            "`Pattern and path valid?` rejects empty search requests and missing search roots before ripgrep is invoked.",
            "`Any results left?` is the final branch after ripgrep execution, relativization, and result-entry pagination.",
        ],
        decisions_zh=[
            "`pattern 和路径是否有效？` 用来在调用 ripgrep 之前尽早拒绝空搜索请求和缺失搜索根路径。",
            "`是否还有结果？` 是 ripgrep 执行、结果相对化和结果条目分页之后的最终分支。",
        ],
        hotspots_en=[
            "The biggest engine-level gap is gone because Go now also runs a shared ripgrep-backed path instead of a hand-rolled scanner.",
            "The remaining differences are mostly around surrounding runtime integration and structured result shaping, not raw search semantics.",
        ],
        hotspots_zh=[
            "最大的引擎级差距已经收掉了，因为 Go 现在也运行共享 ripgrep 后端，而不是手搓扫描器。",
            "剩余差异主要在外围运行时集成和结构化结果塑形，而不是原始搜索语义。",
        ],
    ),
    "ListMcpResourcesTool": spec(
        nodes=[
            n("A", "start", "Start", "开始"),
            n("B", "step", "Parse optional server name", "解析可选 server 名称"),
            n("C", "decision", "Specific server requested?", "是否指定了具体 server？"),
            n("D", "step", "List all cached servers", "列出所有缓存的 server"),
            n("E", "result", "Return aggregated resource list", "返回聚合后的资源列表"),
            n("F", "step", "Resolve or connect target server", "解析或连接目标 server"),
            n("G", "decision", "Cached / ready connection available?", "是否已有缓存 / 就绪连接？"),
            n("H", "step", "Call ListResources on live client", "在活跃 client 上调用 ListResources"),
            n("I", "result", "Return server resource list", "返回单 server 资源列表"),
            n("X1", "gap", "Original still has richer runtime metadata around MCP integration", "原版在 MCP 集成周边仍有更丰富的运行时元数据"),
        ],
        edges=[
            e("A", "B"),
            e("B", "C"),
            e("C", "D", "No", "否"),
            e("C", "F", "Yes", "是"),
            e("D", "E"),
            e("F", "G"),
            e("G", "I", "Yes", "是"),
            e("G", "H", "No", "否"),
            e("H", "I"),
            e("I", "X1", style="note"),
        ],
        decisions_en=[
            "`Specific server requested?` decides whether the tool aggregates cached resources across all servers or drills into one server's live / cached state.",
            "`Cached / ready connection available?` chooses between reusing cached MCP metadata and actively listing resources from a live connection.",
        ],
        decisions_zh=[
            "`是否指定了具体 server？` 决定工具是聚合所有 server 的缓存资源，还是深入一个 server 的 live / cached 状态。",
            "`是否已有缓存 / 就绪连接？` 决定是复用缓存的 MCP 元数据，还是从活跃连接上主动列出资源。",
        ],
        hotspots_en=[
            "The active MCP listing path is fairly close in both implementations.",
            "The remaining gap is mostly the richer original runtime metadata and surrounding integration, not the core list flow.",
        ],
        hotspots_zh=[
            "在激活的 MCP 列表路径上，两边实现已经比较接近。",
            "剩余差距主要在原版更丰富的运行时元数据和外围集成，而不在核心 list 流程本身。",
        ],
    ),
    "NotebookEditTool": spec(
        nodes=[
            n("A", "start", "Start", "开始"),
            n("B", "step", "Parse notebook edit request", "解析 notebook 编辑请求"),
            n("C", "decision", "Notebook path valid?", "notebook 路径是否有效？"),
            n("D", "result", "Return validation error", "返回校验错误"),
            n("E", "step", "Read and parse notebook JSON", "读取并解析 notebook JSON"),
            n("F", "decision", "Edit mode?", "编辑模式是什么？"),
            n("G", "step", "Replace cell", "替换单元格"),
            n("H", "step", "Insert cell", "插入单元格"),
            n("I", "step", "Delete cell", "删除单元格"),
            n("J", "result", "Write notebook and return summary", "写回 notebook 并返回摘要"),
            n("X1", "gap", "Original keeps richer notebook metadata and output semantics", "原版保留了更丰富的 notebook 元数据和输出语义"),
        ],
        edges=[
            e("A", "B"),
            e("B", "C"),
            e("C", "D", "No", "否"),
            e("C", "E", "Yes", "是"),
            e("E", "F"),
            e("F", "G", "Replace", "替换"),
            e("F", "H", "Insert", "插入"),
            e("F", "I", "Delete", "删除"),
            e("G", "J"),
            e("H", "J"),
            e("I", "J"),
            e("J", "X1", style="note"),
        ],
        decisions_en=[
            "`Notebook path valid?` covers the required path and the `.ipynb` extension guard.",
            "`Edit mode?` routes the operation into replace, insert, or delete cell logic.",
        ],
        decisions_zh=[
            "`notebook 路径是否有效？` 覆盖必填路径以及 `.ipynb` 扩展名保护。",
            "`编辑模式是什么？` 用来把操作分流到 replace、insert 或 delete 单元格逻辑。",
        ],
        hotspots_en=[
            "The core notebook mutation flow is already aligned: load JSON, mutate cells, write back.",
            "The remaining parity gap is around richer metadata and notebook-output semantics, not basic cell editing.",
        ],
        hotspots_zh=[
            "核心 notebook 变更流程已经对齐：加载 JSON、修改单元格、写回。",
            "剩余一致性差异主要在更丰富的元数据和 notebook 输出语义，而不是基础单元格编辑。",
        ],
    ),
    "ReadMcpResourceTool": spec(
        nodes=[
            n("A", "start", "Start", "开始"),
            n("B", "step", "Parse server and uri", "解析 server 和 uri"),
            n("C", "decision", "Required fields present?", "必填字段是否齐全？"),
            n("D", "result", "Return validation error", "返回校验错误"),
            n("E", "step", "Connect target MCP server", "连接目标 MCP server"),
            n("F", "decision", "HTTP fallback path?", "是否走 HTTP 回退路径？"),
            n("G", "step", "Read resource through HTTP bridge", "通过 HTTP bridge 读取资源"),
            n("H", "step", "Read resource through live MCP client", "通过活跃 MCP client 读取资源"),
            n("I", "result", "Return resource content", "返回资源内容"),
            n("X1", "gap", "Original wraps the same read in richer runtime result plumbing", "原版会把同样的读取包进更丰富的运行时结果管线"),
        ],
        edges=[
            e("A", "B"),
            e("B", "C"),
            e("C", "D", "No", "否"),
            e("C", "E", "Yes", "是"),
            e("E", "F"),
            e("F", "G", "Yes", "是"),
            e("F", "H", "No", "否"),
            e("G", "I"),
            e("H", "I"),
            e("I", "X1", style="note"),
        ],
        decisions_en=[
            "`Required fields present?` rejects requests that do not identify both a server and a concrete resource URI.",
            "`HTTP fallback path?` decides whether the read goes through an HTTP bridge or a live MCP protocol client.",
        ],
        decisions_zh=[
            "`必填字段是否齐全？` 用来拒绝那些既没有 server 也没有具体资源 URI 的请求。",
            "`是否走 HTTP 回退路径？` 决定读取是通过 HTTP bridge，还是通过活跃的 MCP 协议 client。",
        ],
        hotspots_en=[
            "The active resource read path is already close between Go and the original.",
            "The remaining difference is mostly in surrounding runtime result plumbing and metadata, not in the core fetch itself.",
        ],
        hotspots_zh=[
            "在激活的资源读取路径上，Go 和原版已经比较接近。",
            "剩余差异主要在外围的运行时结果管线和元数据，而不是核心读取本身。",
        ],
    ),
    "RemoteTriggerTool": spec(
        nodes=[
            n("A", "start", "Start", "开始"),
            n("B", "step", "Parse action, trigger_id, body", "解析 action、trigger_id、body"),
            n("C", "decision", "Legacy webhook input present?", "是否存在 legacy webhook 输入？"),
            n("D", "step", "Take legacy webhook branch", "进入 legacy webhook 分支"),
            n("E", "decision", "Action valid?", "Action 是否有效？"),
            n("F", "result", "Return validation error", "返回校验错误"),
            n("G", "step", "Resolve token, base URL, org UUID", "解析 token、base URL 和 org UUID"),
            n("H", "step", "Map action to request", "把 action 映射为请求"),
            n("I", "step", "Send CCR API request", "发送 CCR API 请求"),
            n("J", "result", "Return status + JSON body", "返回 status + JSON body"),
            n("X1", "gap", "Original schema only exposes CCR API fields; Go still carries a hidden legacy webhook path", "原版 schema 只暴露 CCR API 字段；Go 仍保留隐藏的 legacy webhook 路径"),
            n("X2", "gap", "Original also gates availability through feature and policy checks", "原版还会通过 feature 和 policy 检查控制可用性"),
        ],
        edges=[
            e("A", "B"),
            e("B", "C"),
            e("C", "D", "Yes", "是"),
            e("C", "E", "No", "否"),
            e("D", "J"),
            e("E", "F", "No", "否"),
            e("E", "G", "Yes", "是"),
            e("G", "H"),
            e("H", "I"),
            e("I", "J"),
            e("B", "X1", style="note"),
            e("G", "X2", style="note"),
        ],
        decisions_en=[
            "`Legacy webhook input present?` is the Go-only branch that bypasses the stricter CCR-API-only shape used by the original.",
            "`Action valid?` covers required action names and trigger-id shape before any network request is sent.",
        ],
        decisions_zh=[
            "`是否存在 legacy webhook 输入？` 是 Go 独有的分支，它绕过了原版更严格的 CCR-API-only 输入形状。",
            "`Action 是否有效？` 覆盖必填 action 名称和 trigger_id 形状校验，先于任何网络请求发生。",
        ],
        hotspots_en=[
            "The core authenticated CCR request path is now close enough to talk to the real API.",
            "The biggest remaining divergence is shape and availability control: Go still carries a legacy branch, while the original is stricter and more explicitly gated.",
        ],
        hotspots_zh=[
            "核心的带认证 CCR 请求路径现在已经足够接近，可以访问真实 API。",
            "最大的剩余分歧在输入形状和可用性控制上：Go 仍保留 legacy 分支，而原版更严格、gate 更明确。",
        ],
    ),
    "SendMessageTool": spec(
        nodes=[
            n("A", "start", "Start", "开始"),
            n("B", "step", "Validate target and message", "校验目标和消息"),
            n("C", "decision", "Structured control message?", "是否为结构化控制消息？"),
            n("D", "step", "Route shutdown / plan-approval mailbox flow", "路由 shutdown / plan-approval 邮箱流"),
            n("E", "decision", "UDS target?", "是否为 UDS 目标？"),
            n("F", "step", "Send over local UDS path", "通过本地 UDS 路径发送"),
            n("G", "decision", "Local agent target?", "是否为本地 agent 目标？"),
            n("H", "step", "Queue or resume local agent session", "排队或续跑本地 agent 会话"),
            n("I", "decision", "Broadcast target *?", "是否为广播目标 *？"),
            n("J", "step", "Write team mailbox message", "写入 team 邮箱消息"),
            n("K", "result", "Return routing result", "返回路由结果"),
            n("X1", "gap", "Original also had bridge / remote-control routing; that path is intentionally removed in Go scope", "原版还包含 bridge / remote-control 路由；该路径已被有意移出 Go 范围"),
            n("X2", "gap", "Go local-agent continuation works only for retained in-memory sessions", "Go 的本地 agent 续跑只适用于保留在内存中的会话"),
            n("X3", "gap", "Go adds a MessageBus-style fallback path that the original does not expose", "Go 额外加入了原版未暴露的 MessageBus 式回退路径"),
        ],
        edges=[
            e("A", "B"),
            e("B", "C"),
            e("C", "D", "Yes", "是"),
            e("C", "E", "No", "否"),
            e("D", "K"),
            e("E", "F", "Yes", "是"),
            e("E", "G", "No", "否"),
            e("F", "K"),
            e("G", "H", "Yes", "是"),
            e("G", "I", "No", "否"),
            e("H", "K"),
            e("I", "J", "Yes / No", "是 / 否"),
            e("J", "K"),
            e("B", "X1", style="note"),
            e("H", "X2", style="note"),
            e("J", "X3", style="note"),
        ],
        decisions_en=[
            "`Structured control message?` decides whether the tool is routing control-plane mailbox traffic instead of free-form text.",
            "`UDS target?` separates local peer-session delivery from normal team / agent routing.",
            "`Local agent target?` determines whether the runtime should resume or queue a retained local agent session.",
            "`Broadcast target *?` controls whether the same mailbox message fans out to the whole team or goes to one recipient.",
        ],
        decisions_zh=[
            "`是否为结构化控制消息？` 决定工具是在路由控制面邮箱消息，还是普通自由文本。",
            "`是否为 UDS 目标？` 用来区分本地 peer-session 发送与普通 team / agent 路由。",
            "`是否为本地 agent 目标？` 决定运行时是否应该续跑或排队一个已保留的本地 agent 会话。",
            "`是否为广播目标 *？` 控制同一条邮箱消息是扇出到整个 team，还是只发给一个接收者。",
        ],
        hotspots_en=[
            "The supported Go subset is still useful: teammate mailboxes, local retained agents, and `uds:` peers all work.",
            "The clearest parity break is explicit and intentional: the original bridge / remote-control path is not part of Go scope anymore.",
            "Even inside the supported subset, original continuation and shutdown semantics remain richer than Go's in-memory approximation.",
        ],
        hotspots_zh=[
            "Go 当前支持的子集仍然有实际价值：teammate 邮箱、本地保留 agent，以及 `uds:` peer 都能工作。",
            "最清晰的一处一致性断点是显式且有意的：原版的 bridge / remote-control 路径已不再属于 Go 范围。",
            "即便在支持的子集内，原版的 continuation 和 shutdown 语义仍然比 Go 的内存近似实现更丰富。",
        ],
    ),
    "SkillTool": spec(
        nodes=[
            n("A", "start", "Start", "开始"),
            n("B", "step", "Parse skill and args", "解析 skill 和 args"),
            n("C", "decision", "Skill name present?", "是否提供 skill 名？"),
            n("D", "result", "Return validation error", "返回校验错误"),
            n("E", "step", "Lookup installed skill", "查找已安装 skill"),
            n("F", "decision", "Skill found?", "是否找到 skill？"),
            n("G", "result", "Return not-found + available skills", "返回未找到结果和可用 skill 列表"),
            n("H", "step", "Prepare substituted skill content", "准备替换后的 skill 内容"),
            n("I", "result", "Return skill payload", "返回 skill 载荷"),
            n("X1", "gap", "Original integrates skill execution more deeply into the runtime", "原版把 skill 执行更深地集成进运行时"),
        ],
        edges=[
            e("A", "B"),
            e("B", "C"),
            e("C", "D", "No", "否"),
            e("C", "E", "Yes", "是"),
            e("E", "F"),
            e("F", "G", "No", "否"),
            e("F", "H", "Yes", "是"),
            e("H", "I"),
            e("H", "X1", style="note"),
        ],
        decisions_en=[
            "`Skill name present?` rejects empty invocations before any manager lookup happens.",
            "`Skill found?` decides whether the tool can expand a real installed skill or must stop with an availability message.",
        ],
        decisions_zh=[
            "`是否提供 skill 名？` 用来在任何 manager lookup 发生前拒绝空调用。",
            "`是否找到 skill？` 决定工具是展开一个真实已安装的 skill，还是只能返回可用性提示。",
        ],
        hotspots_en=[
            "The shared flow is simple and explicit: parse, lookup, substitute, return.",
            "The remaining difference is mostly runtime depth: the original skill system is woven more deeply into the wider assistant runtime.",
        ],
        hotspots_zh=[
            "共享流程简单直接：解析、查找、替换、返回。",
            "剩余差异主要在运行时深度：原版 skill 系统和更大的 assistant runtime 织得更紧。",
        ],
    ),
    "TaskCreateTool": spec(
        nodes=[
            n("A", "start", "Start", "开始"),
            n("B", "step", "Parse task fields", "解析任务字段"),
            n("C", "step", "Resolve task-list scope", "解析任务列表作用域"),
            n("D", "step", "Create task record", "创建任务记录"),
            n("E", "step", "Persist task", "持久化任务"),
            n("F", "result", "Return created task", "返回已创建任务"),
            n("X1", "gap", "Original only exposes this tool when task-v2 is enabled", "原版只会在 task-v2 打开时暴露这个工具"),
            n("X2", "gap", "Original also runs task-created hooks and richer UI expansion", "原版还会运行 task-created hooks，并做更丰富的 UI 展开"),
        ],
        edges=[
            e("A", "B"),
            e("B", "C"),
            e("C", "D"),
            e("D", "E"),
            e("E", "F"),
            e("B", "X1", style="note"),
            e("D", "X2", style="note"),
        ],
        decisions_en=[
            "This tool's main hidden decision is scope resolution: which task list the new task belongs to in the current session / team context.",
        ],
        decisions_zh=[
            "这个工具最重要的隐含决策是作用域解析：新任务到底归属于当前 session / team 上下文中的哪一个任务列表。",
        ],
        hotspots_en=[
            "The shared happy path is create-and-persist.",
            "The original wraps that path in task-v2 gating, hook execution, and richer UI/runtime side effects that Go does not yet mirror.",
        ],
        hotspots_zh=[
            "共享 happy path 就是创建并持久化。",
            "原版会在这条路径外包上 task-v2 gate、hook 执行，以及更丰富的 UI / runtime 副作用，而 Go 还没有镜像这些行为。",
        ],
    ),
    "TaskGetTool": spec(
        nodes=[
            n("A", "start", "Start", "开始"),
            n("B", "step", "Parse task id", "解析任务 id"),
            n("C", "step", "Resolve task-list scope", "解析任务列表作用域"),
            n("D", "decision", "Task found?", "是否找到任务？"),
            n("E", "result", "Return not-found result", "返回未找到结果"),
            n("F", "result", "Return task object", "返回任务对象"),
            n("X1", "gap", "Original only exposes this tool when task-v2 is enabled", "原版只会在 task-v2 打开时暴露这个工具"),
            n("X2", "gap", "Original task lookup can resolve richer team / teammate scopes", "原版任务查询能解析更丰富的 team / teammate 作用域"),
        ],
        edges=[
            e("A", "B"),
            e("B", "C"),
            e("C", "D"),
            e("D", "E", "No", "否"),
            e("D", "F", "Yes", "是"),
            e("B", "X1", style="note"),
            e("C", "X2", style="note"),
        ],
        decisions_en=[
            "`Task found?` is the visible branch, but the more important hidden branch is scope resolution before lookup starts.",
        ],
        decisions_zh=[
            "`是否找到任务？` 是可见分支，但更关键的隐含分支其实是查找开始前的作用域解析。",
        ],
        hotspots_en=[
            "Lookup itself is straightforward once the correct task list is resolved.",
            "The main differences are exposure gating and the richer original scope-resolution logic for teams and teammates.",
        ],
        hotspots_zh=[
            "一旦解析到正确的任务列表，查询本身就很直接。",
            "主要差异在工具暴露 gate，以及原版针对 team 和 teammate 更丰富的作用域解析逻辑。",
        ],
    ),
    "TaskListTool": spec(
        nodes=[
            n("A", "start", "Start", "开始"),
            n("B", "step", "Resolve task-list scope", "解析任务列表作用域"),
            n("C", "step", "Load tasks from store", "从存储中加载任务"),
            n("D", "step", "Sort and format tasks", "排序并格式化任务"),
            n("E", "result", "Return task list", "返回任务列表"),
            n("X1", "gap", "Original only exposes this tool when task-v2 is enabled", "原版只会在 task-v2 打开时暴露这个工具"),
            n("X2", "gap", "Original task-list resolution is richer across leader / teammate contexts", "原版在 leader / teammate 上下文下的任务列表解析更丰富"),
        ],
        edges=[
            e("A", "B"),
            e("B", "C"),
            e("C", "D"),
            e("D", "E"),
            e("A", "X1", style="note"),
            e("B", "X2", style="note"),
        ],
        decisions_en=[
            "As with other task tools, the critical hidden decision is which task list is being read in the current session context.",
        ],
        decisions_zh=[
            "和其他任务工具一样，关键的隐含决策是：在当前 session 上下文中到底读取哪一个任务列表。",
        ],
        hotspots_en=[
            "The visible flow is simple: resolve scope, load, sort, return.",
            "The real divergence is around exposure gating and richer original task-list scope resolution.",
        ],
        hotspots_zh=[
            "可见流程很简单：解析作用域、加载、排序、返回。",
            "真正的差异在工具暴露 gate，以及原版更丰富的任务列表作用域解析上。",
        ],
    ),
    "TaskOutputTool": spec(
        nodes=[
            n("A", "start", "Start", "开始"),
            n("B", "step", "Parse task id and wait options", "解析任务 id 和等待选项"),
            n("C", "step", "Resolve background task handle", "解析后台任务句柄"),
            n("D", "decision", "Task found?", "是否找到任务？"),
            n("E", "result", "Return not-found result", "返回未找到结果"),
            n("F", "decision", "Block and wait?", "是否阻塞等待？"),
            n("G", "step", "Wait for state change or completion", "等待状态变化或完成"),
            n("H", "step", "Read buffered or persisted output", "读取缓冲输出或持久化输出"),
            n("I", "step", "Truncate and format task output", "截断并格式化任务输出"),
            n("J", "result", "Return task output", "返回任务输出"),
            n("X1", "gap", "Go only serves background-manager tasks; original supports a broader task runtime", "Go 只服务于 background-manager 任务；原版支持更宽的任务运行时"),
            n("X2", "gap", "Original also handles notified flags, progress, and richer local-agent output synthesis", "原版还会处理 notified 标记、进度，以及更丰富的本地 agent 输出合成"),
        ],
        edges=[
            e("A", "B"),
            e("B", "C"),
            e("C", "D"),
            e("D", "E", "No", "否"),
            e("D", "F", "Yes", "是"),
            e("F", "G", "Yes", "是"),
            e("F", "H", "No", "否"),
            e("G", "H"),
            e("H", "I"),
            e("I", "J"),
            e("C", "X1", style="note"),
            e("I", "X2", style="note"),
        ],
        decisions_en=[
            "`Task found?` decides whether the tool can inspect a live background handle at all.",
            "`Block and wait?` controls whether output is returned immediately or after the runtime waits for more task progress.",
        ],
        decisions_zh=[
            "`是否找到任务？` 决定工具能否真正查看一个活跃后台句柄。",
            "`是否阻塞等待？` 控制是立即返回输出，还是等待更多任务进度之后再返回。",
        ],
        hotspots_en=[
            "The Go path is much narrower because it only knows about the background task manager's task types.",
            "The original task-output runtime covers more task kinds and richer post-processing around notifications, progress, and synthesized agent output.",
        ],
        hotspots_zh=[
            "Go 路径之所以明显更窄，是因为它只认识 background task manager 里的那几类任务。",
            "原版 task-output 运行时覆盖了更多任务类型，并且在通知、进度和 agent 输出合成上有更丰富的后处理。",
        ],
    ),
    "TaskStopTool": spec(
        nodes=[
            n("A", "start", "Start", "开始"),
            n("B", "step", "Parse task id", "解析任务 id"),
            n("C", "step", "Resolve running task handle", "解析运行中的任务句柄"),
            n("D", "decision", "Task found and stoppable?", "任务是否存在且可停止？"),
            n("E", "result", "Return not-found / unsupported result", "返回未找到 / 不支持结果"),
            n("F", "step", "Cancel task", "取消任务"),
            n("G", "result", "Return stop summary", "返回停止摘要"),
            n("X1", "gap", "Go only stops background-manager task types", "Go 只能停止 background-manager 任务类型"),
            n("X2", "gap", "Original stop flow spans a broader task runtime and notification semantics", "原版的 stop 流程覆盖更宽的任务运行时和通知语义"),
        ],
        edges=[
            e("A", "B"),
            e("B", "C"),
            e("C", "D"),
            e("D", "E", "No", "否"),
            e("D", "F", "Yes", "是"),
            e("F", "G"),
            e("C", "X1", style="note"),
            e("F", "X2", style="note"),
        ],
        decisions_en=[
            "`Task found and stoppable?` decides whether the tool can cancel a real running task or only explain that the task is missing / unsupported.",
        ],
        decisions_zh=[
            "`任务是否存在且可停止？` 决定工具是可以取消一个真实运行中的任务，还是只能解释任务缺失 / 不受支持。",
        ],
        hotspots_en=[
            "The stop path is simple once a cancellable task handle exists.",
            "The main difference is task coverage: Go stops only background-manager tasks, while the original covers a richer task runtime.",
        ],
        hotspots_zh=[
            "一旦存在可取消的任务句柄，stop 路径本身很简单。",
            "主要差异在任务覆盖面：Go 只能停止 background-manager 任务，而原版覆盖的是更丰富的任务运行时。",
        ],
    ),
    "TaskUpdateTool": spec(
        nodes=[
            n("A", "start", "Start", "开始"),
            n("B", "step", "Parse id and optional fields", "解析 id 和可选字段"),
            n("C", "step", "Resolve task-list scope", "解析任务列表作用域"),
            n("D", "decision", "Task found?", "是否找到任务？"),
            n("E", "result", "Return not-found result", "返回未找到结果"),
            n("F", "step", "Apply field updates", "应用字段更新"),
            n("G", "decision", "Task completed by this update?", "这次更新是否把任务改成已完成？"),
            n("H", "step", "Persist updated task", "持久化更新后的任务"),
            n("I", "result", "Return updated task", "返回更新后的任务"),
            n("X1", "gap", "Original only exposes this tool when task-v2 is enabled", "原版只会在 task-v2 打开时暴露这个工具"),
            n("X2", "gap", "Original also runs completion hooks, mailbox side effects, and richer UI behavior", "原版还会运行完成 hooks、邮箱副作用以及更丰富的 UI 行为"),
            n("X3", "gap", "Go treats empty strings as not provided for several fields", "Go 会把若干字段里的空字符串当作“未提供”"),
        ],
        edges=[
            e("A", "B"),
            e("B", "C"),
            e("C", "D"),
            e("D", "E", "No", "否"),
            e("D", "F", "Yes", "是"),
            e("F", "G"),
            e("G", "H", "Yes / No", "是 / 否"),
            e("H", "I"),
            e("A", "X1", style="note"),
            e("G", "X2", style="note"),
            e("F", "X3", style="note"),
        ],
        decisions_en=[
            "`Task found?` decides whether updates can even be applied.",
            "`Task completed by this update?` is where the original branches into task-completion hooks and side effects.",
        ],
        decisions_zh=[
            "`是否找到任务？` 决定更新是否有机会真正落地。",
            "`这次更新是否把任务改成已完成？` 是原版切入 task-completion hooks 和副作用分支的位置。",
        ],
        hotspots_en=[
            "The shared path is apply-update-and-persist.",
            "The original wraps completion transitions in hooks, mailbox side effects, and richer UI changes; Go currently does not.",
            "Go also simplifies several field semantics by treating empty strings as missing input.",
        ],
        hotspots_zh=[
            "共享路径就是应用更新并持久化。",
            "原版会把任务完成状态切换包进 hooks、邮箱副作用和更丰富的 UI 变化里；Go 当前没有这些语义。",
            "此外，Go 还通过把空字符串视为缺失输入，简化了若干字段语义。",
        ],
    ),
    "TeamCreateTool": spec(
        nodes=[
            n("A", "start", "Start", "开始"),
            n("B", "step", "Validate team_name", "校验 team_name"),
            n("C", "decision", "Leader already owns a team?", "leader 是否已经拥有 team？"),
            n("D", "result", "Return rejection", "返回拒绝结果"),
            n("E", "step", "Choose unique team name", "选择唯一 team 名称"),
            n("F", "step", "Build lead team context", "构造 lead team 上下文"),
            n("G", "step", "Persist team file and cleanup metadata", "持久化 team 文件和清理元数据"),
            n("H", "step", "Update in-memory team runtime", "更新内存中的 team 运行时"),
            n("I", "result", "Return team_name and lead_agent_id", "返回 team_name 和 lead_agent_id"),
            n("X1", "gap", "Original mostly creates swarm scaffolding; teammate spawn happens later through Agent", "原版主要创建 swarm 脚手架；teammate 会在之后通过 Agent 创建"),
            n("X2", "gap", "Go can eagerly register coordinator agents in-memory", "Go 可以提前在内存中注册 coordinator agents"),
        ],
        edges=[
            e("A", "B"),
            e("B", "C"),
            e("C", "D", "Yes", "是"),
            e("C", "E", "No", "否"),
            e("E", "F"),
            e("F", "G"),
            e("G", "H"),
            e("H", "I"),
            e("F", "X1", style="note"),
            e("H", "X2", style="note"),
        ],
        decisions_en=[
            "`Leader already owns a team?` prevents one leader session from accumulating conflicting team state.",
        ],
        decisions_zh=[
            "`leader 是否已经拥有 team？` 用来阻止同一个 leader 会话积累互相冲突的 team 状态。",
        ],
        hotspots_en=[
            "Both versions persist lead-owned team state and prepare future coordination.",
            "The main difference is when teammates are materialized: the original mostly scaffolds first, while Go can register more runtime state eagerly.",
        ],
        hotspots_zh=[
            "两边都会持久化由 lead 拥有的 team 状态，并为后续协同做准备。",
            "主要差异在 teammate 的物化时机：原版更多是先搭脚手架，而 Go 可以更早注册运行时状态。",
        ],
    ),
    "TeamDeleteTool": spec(
        nodes=[
            n("A", "start", "Start", "开始"),
            n("B", "step", "Load current team", "加载当前 team"),
            n("C", "decision", "Team exists?", "team 是否存在？"),
            n("D", "result", "Return no-op success", "返回 no-op 成功结果"),
            n("E", "step", "Inspect non-lead members", "检查非 lead 成员"),
            n("F", "decision", "Any active members?", "是否存在 active 成员？"),
            n("G", "result", "Refuse cleanup", "拒绝清理"),
            n("H", "step", "Remove team state and files", "删除 team 状态和文件"),
            n("I", "result", "Return delete success", "返回删除成功"),
            n("X1", "gap", "Original also removes worktrees, task dirs, and richer swarm UI/session state", "原版还会删除 worktree、任务目录，以及更丰富的 swarm UI / 会话状态"),
        ],
        edges=[
            e("A", "B"),
            e("B", "C"),
            e("C", "D", "No", "否"),
            e("C", "E", "Yes", "是"),
            e("E", "F"),
            e("F", "G", "Yes", "是"),
            e("F", "H", "No", "否"),
            e("H", "I"),
            e("H", "X1", style="note"),
        ],
        decisions_en=[
            "`Team exists?` decides whether deletion is meaningful or only a harmless no-op.",
            "`Any active members?` is the safety gate that prevents tearing down team state while live members still exist.",
        ],
        decisions_zh=[
            "`team 是否存在？` 决定删除是否有意义，还是只是一次无害 no-op。",
            "`是否存在 active 成员？` 是安全 gate，用来阻止在仍有活跃成员时拆除 team 状态。",
        ],
        hotspots_en=[
            "The active-member guard is now close.",
            "The remaining divergence is cleanup depth: the original tears down more worktree, task-directory, and swarm-session state than Go currently does.",
        ],
        hotspots_zh=[
            "active-member 保护现在已经比较接近。",
            "剩余差异在清理深度：原版会拆除比 Go 当前更多的 worktree、任务目录和 swarm 会话状态。",
        ],
    ),
    "TodoWriteTool": spec(
        nodes=[
            n("A", "start", "Start", "开始"),
            n("B", "step", "Parse todo list", "解析 todo 列表"),
            n("C", "decision", "Todo payload valid?", "todo 载荷是否有效？"),
            n("D", "result", "Return validation error", "返回校验错误"),
            n("E", "step", "Resolve current session todo store", "解析当前会话的 todo 存储"),
            n("F", "step", "Persist todo list", "持久化 todo 列表"),
            n("G", "result", "Return verification nudge", "返回 verification 提示"),
            n("X1", "gap", "Original only exposes TodoWrite when task-v2 is disabled", "原版只会在 task-v2 关闭时暴露 TodoWrite"),
            n("X2", "gap", "Original allows empty lists to clear todos; Go rejects them", "原版允许用空列表清空 todos；Go 会拒绝"),
            n("X3", "gap", "Original stores todos in app state / transcript recovery; Go persists a local JSON file", "原版把 todos 存进 app state / transcript 恢复链路；Go 则持久化本地 JSON 文件"),
        ],
        edges=[
            e("A", "B"),
            e("B", "C"),
            e("C", "D", "No", "否"),
            e("C", "E", "Yes", "是"),
            e("E", "F"),
            e("F", "G"),
            e("A", "X1", style="note"),
            e("B", "X2", style="note"),
            e("E", "X3", style="note"),
        ],
        decisions_en=[
            "`Todo payload valid?` decides whether the runtime can accept and persist the todo list at all.",
        ],
        decisions_zh=[
            "`todo 载荷是否有效？` 决定运行时是否可以接受并持久化这份 todo 列表。",
        ],
        hotspots_en=[
            "The Go path is explicit and local-file-backed.",
            "The biggest differences are gating, empty-list semantics, and where todo state lives and gets restored from.",
        ],
        hotspots_zh=[
            "Go 路径很明确，而且是本地文件持久化。",
            "最大的差异在工具暴露 gate、空列表语义，以及 todo 状态到底存在哪里、从哪里恢复。",
        ],
    ),
    "ToolSearchTool": spec(
        nodes=[
            n("A", "start", "Start", "开始"),
            n("B", "step", "Parse query and max_results", "解析 query 和 max_results"),
            n("C", "decision", "Query present?", "是否提供 query？"),
            n("D", "result", "Return validation error", "返回校验错误"),
            n("E", "step", "Build deferred-tool pool from registry metadata", "根据 registry 元信息构建 deferred 工具池"),
            n("F", "decision", "select:<name> query?", "是否为 select:<name> 查询？"),
            n("G", "step", "Resolve exact selections, including already-loaded no-op selections", "解析精确选择，并允许已加载工具走 no-op 选择"),
            n("H", "step", "Run keyword ranking over deferred tools and hints", "在 deferred 工具及提示上做关键词排序"),
            n("I", "decision", "Any tool matches?", "是否命中工具？"),
            n("J", "result", "Return empty-state summary", "返回空状态摘要"),
            n("K", "result", "Return structured tool_reference result + text summary", "返回结构化 tool_reference 结果和文本摘要"),
            n("L", "step", "Loop records loaded tool names for later turns", "循环记录已加载工具名，供后续轮次使用"),
            n("M", "result", "Next turn exposes loaded tool schemas", "下一轮暴露已加载工具的 schema"),
            n("X1", "gap", "Original still has deeper MCP pending-state and prompt-generation plumbing", "原版仍有更深的 MCP pending-state 和 prompt 生成管线"),
            n("X2", "gap", "Provider-native defer_loading / beta handling is still richer in the original", "provider 原生 defer_loading / beta 处理在原版中仍更完整"),
        ],
        edges=[
            e("A", "B"),
            e("B", "C"),
            e("C", "D", "No", "否"),
            e("C", "E", "Yes", "是"),
            e("E", "F"),
            e("F", "G", "Yes", "是"),
            e("F", "H", "No", "否"),
            e("G", "I"),
            e("H", "I"),
            e("I", "J", "No", "否"),
            e("I", "K", "Yes", "是"),
            e("K", "L"),
            e("L", "M"),
            e("E", "X1", style="note"),
            e("K", "X2", style="note"),
        ],
        decisions_en=[
            "`Query present?` rejects empty tool-search requests before any registry scan.",
            "`select:<name> query?` decides whether the tool should do deterministic direct selection or ranked keyword discovery.",
            "`Any tool matches?` decides whether the tool emits structured tool references or a clear empty-state summary.",
        ],
        decisions_zh=[
            "`是否提供 query？` 用来在任何 registry 扫描前拒绝空的工具搜索请求。",
            "`是否为 select:<name> 查询？` 决定工具是走确定性的直接选择，还是走关键词排序发现。",
            "`是否命中工具？` 决定工具是输出结构化 tool reference，还是明确的空状态摘要。",
        ],
        hotspots_en=[
            "Go now mirrors the important discovery loop: deferred tools are hidden up front, ToolSearch can discover them, and the loop carries loaded-tool state into later turns.",
            "The remaining gaps are concentrated in MCP pending-state awareness, richer prompt/description generation, and native provider-side defer-loading infrastructure.",
        ],
        hotspots_zh=[
            "Go 现在已经对齐了关键发现闭环：先隐藏 deferred 工具，再由 ToolSearch 发现，并把 loaded-tool 状态带到后续轮次。",
            "剩余差距已经集中到 MCP pending-state 感知、更丰富的 prompt/description 生成，以及 provider 原生 defer-loading 基础设施。",
        ],
    ),
    "WebFetchTool": spec(
        nodes=[
            n("A", "start", "Start", "开始"),
            n("B", "step", "Parse url and prompt", "解析 url 和 prompt"),
            n("C", "decision", "URL / prompt valid?", "URL / prompt 是否有效？"),
            n("D", "result", "Return validation error", "返回校验错误"),
            n("E", "step", "Run SSRF and domain checks", "执行 SSRF 和域名检查"),
            n("F", "decision", "Cache hit?", "是否命中缓存？"),
            n("G", "result", "Return cached content", "返回缓存内容"),
            n("H", "step", "Fetch URL with redirect guard", "带重定向保护地抓取 URL"),
            n("I", "decision", "HTTP success?", "HTTP 是否成功？"),
            n("J", "result", "Return HTTP error", "返回 HTTP 错误"),
            n("K", "step", "Read and normalize payload", "读取并规范化载荷"),
            n("L", "result", "Return fetched content", "返回抓取内容"),
            n("X1", "gap", "Original has a richer permission path and redirect policy", "原版有更丰富的权限路径和重定向策略"),
            n("X2", "gap", "Original converts HTML to markdown, persists binaries, and semantically applies the prompt", "原版会把 HTML 转为 markdown、持久化二进制内容，并语义化应用 prompt"),
        ],
        edges=[
            e("A", "B"),
            e("B", "C"),
            e("C", "D", "No", "否"),
            e("C", "E", "Yes", "是"),
            e("E", "F"),
            e("F", "G", "Yes", "是"),
            e("F", "H", "No", "否"),
            e("H", "I"),
            e("I", "J", "No", "否"),
            e("I", "K", "Yes", "是"),
            e("K", "L"),
            e("E", "X1", style="note"),
            e("K", "X2", style="note"),
        ],
        decisions_en=[
            "`URL / prompt valid?` ensures the request is well-formed before any network access begins.",
            "`Cache hit?` decides whether the tool can stop at cached content or must perform a real fetch.",
            "`HTTP success?` determines whether the call returns an error result or continues to payload normalization.",
        ],
        decisions_zh=[
            "`URL / prompt 是否有效？` 确保在任何网络访问开始前，请求形状已经正确。",
            "`是否命中缓存？` 决定工具是停在缓存内容上，还是必须执行真实抓取。",
            "`HTTP 是否成功？` 决定这次调用是直接返回错误结果，还是继续进行载荷规范化。",
        ],
        hotspots_en=[
            "The shared fetch path is already recognizable: validate, protect, fetch, normalize, return.",
            "The biggest parity gap is after fetch: the original has richer redirect / permission handling and actually uses the user prompt semantically, not just as echoed text.",
        ],
        hotspots_zh=[
            "共享抓取路径已经很清晰：校验、保护、抓取、规范化、返回。",
            "最大的对齐差距在抓取之后：原版拥有更丰富的重定向 / 权限处理，并且会真正语义化使用用户 prompt，而不是仅仅把它回显出来。",
        ],
    ),
    "WebSearchTool": spec(
        nodes=[
            n("A", "start", "Start", "开始"),
            n("B", "step", "Parse query and filters", "解析 query 和过滤条件"),
            n("C", "decision", "Query present?", "是否提供 query？"),
            n("D", "result", "Return validation error", "返回校验错误"),
            n("E", "decision", "Cache hit?", "是否命中缓存？"),
            n("F", "result", "Return cached search result", "返回缓存的搜索结果"),
            n("G", "step", "Run primary search provider", "运行主搜索提供方"),
            n("H", "decision", "Primary result empty?", "主搜索结果是否为空？"),
            n("I", "step", "Run fallback search", "执行回退搜索"),
            n("J", "step", "Apply domain filters and limits", "应用域名过滤和结果上限"),
            n("K", "decision", "Any results left?", "过滤后是否还有结果？"),
            n("L", "result", "Return no-results output", "返回无结果输出"),
            n("M", "result", "Return search results", "返回搜索结果"),
            n("X1", "gap", "Original uses a server-side model-powered web search tool, not a DDG scraper", "原版使用服务端模型驱动的 web search tool，而不是 DDG 抓取器"),
            n("X2", "gap", "Original rejects allowed_domains + blocked_domains together; Go accepts both", "原版会拒绝同时设置 allowed_domains 和 blocked_domains；Go 接受两者共存"),
            n("X3", "gap", "Go caches by query before filter differences; original search requests include filters each time", "Go 在过滤条件之前按 query 缓存；原版每次搜索请求都会携带过滤条件"),
        ],
        edges=[
            e("A", "B"),
            e("B", "C"),
            e("C", "D", "No", "否"),
            e("C", "E", "Yes", "是"),
            e("E", "F", "Yes", "是"),
            e("E", "G", "No", "否"),
            e("G", "H"),
            e("H", "I", "Yes", "是"),
            e("H", "J", "No", "否"),
            e("I", "J"),
            e("J", "K"),
            e("K", "L", "No", "否"),
            e("K", "M", "Yes", "是"),
            e("G", "X1", style="note"),
            e("B", "X2", style="note"),
            e("E", "X3", style="note"),
        ],
        decisions_en=[
            "`Query present?` rejects empty search requests early.",
            "`Cache hit?` decides whether the tool reuses prior search output or hits the provider again.",
            "`Primary result empty?` controls whether the fallback provider path is used.",
            "`Any results left?` is the final branch after filters and limits are applied.",
        ],
        decisions_zh=[
            "`是否提供 query？` 用来尽早拒绝空搜索请求。",
            "`是否命中缓存？` 决定工具是复用先前搜索输出，还是再次访问提供方。",
            "`主搜索结果是否为空？` 控制是否进入回退提供方路径。",
            "`过滤后是否还有结果？` 是应用过滤条件和上限之后的最终分支。",
        ],
        hotspots_en=[
            "The visible shape is still a search pipeline with provider call, fallback, filtering, and result formatting.",
            "The deepest parity break is architectural: the original search path is model-powered and server-side, while Go implements a DDG-style local search pipeline.",
            "Go also diverges on filter validation and cache-key semantics.",
        ],
        hotspots_zh=[
            "可见形状仍然是一条搜索流水线：调用提供方、回退、过滤、格式化结果。",
            "最深的一处一致性断点是架构层面的：原版搜索路径是模型驱动、服务端执行的，而 Go 实现的是 DDG 风格的本地搜索流水线。",
            "此外，Go 在过滤条件校验和缓存键语义上也存在分歧。",
        ],
    ),
}
