package i18n

// Semantic copy used by session-oriented slash commands. Command arguments,
// file paths, git output, skill metadata, and raw errors remain format values.
const (
	KeyCommandResumeStoreUnavailable Key = "command.resume.store_unavailable"
	KeyCommandResumeListError        Key = "command.resume.list_error"
	KeyCommandResumeNone             Key = "command.resume.none"
	KeyCommandResumeRecent           Key = "command.resume.recent"
	KeyCommandResumeEntry            Key = "command.resume.entry"
	KeyCommandResumeSearchError      Key = "command.resume.search_error"
	KeyCommandResumeMultiple         Key = "command.resume.multiple"
	KeyCommandResumeLoadError        Key = "command.resume.load_error"
	KeyCommandResumeLoaded           Key = "command.resume.loaded"
	KeyCommandResumeLoadedMessages   Key = "command.resume.loaded_messages"

	KeyCommandRenameStoreUnavailable Key = "command.rename.store_unavailable"
	KeyCommandRenameGenerateFailed   Key = "command.rename.generate_failed"
	KeyCommandRenameError            Key = "command.rename.error"
	KeyCommandRenameSucceeded        Key = "command.rename.succeeded"

	KeyCommandForkUsage             Key = "command.fork.usage"
	KeyCommandForkPickerUnavailable Key = "command.fork.picker_unavailable"

	KeyCommandDiffGitMissing    Key = "command.diff.git_missing"
	KeyCommandDiffNotRepository Key = "command.diff.not_repository"
	KeyCommandDiffClean         Key = "command.diff.clean"
	KeyCommandDiffSummary       Key = "command.diff.summary"
	KeyCommandDiffUntracked     Key = "command.diff.untracked"

	KeyCommandReviewGitMissing    Key = "command.review.git_missing"
	KeyCommandReviewNotRepository Key = "command.review.not_repository"
	KeyCommandReviewNoStaged      Key = "command.review.no_staged"
	KeyCommandReviewClean         Key = "command.review.clean"
	KeyCommandReviewAllChanges    Key = "command.review.all_changes"
	KeyCommandReviewStagedChanges Key = "command.review.staged_changes"

	KeyCommandPasteNoImage            Key = "command.paste.no_image"
	KeyCommandPasteConfirmUnavailable Key = "command.paste.confirm_unavailable"
	KeyCommandPasteConfirm            Key = "command.paste.confirm"
	KeyCommandPasteCancelled          Key = "command.paste.cancelled"
	KeyCommandPasteReadError          Key = "command.paste.read_error"
	KeyCommandPasteEmpty              Key = "command.paste.empty"
	KeyCommandPasteReady              Key = "command.paste.ready"

	KeyCommandMemoryResolveError     Key = "command.memory.resolve_error"
	KeyCommandMemoryCreated          Key = "command.memory.created"
	KeyCommandMemoryOpening          Key = "command.memory.opening"
	KeyCommandMemoryEditorError      Key = "command.memory.editor_error"
	KeyCommandMemoryEditorExited     Key = "command.memory.editor_exited"
	KeyCommandMemoryEditorHintSource Key = "command.memory.editor_hint_source"
	KeyCommandMemoryEditorHint       Key = "command.memory.editor_hint"
	KeyCommandMemoryOpened           Key = "command.memory.opened"
	KeyCommandMemoryNoEditor         Key = "command.memory.no_editor"

	KeyCommandSkillsUnavailable         Key = "command.skills.unavailable"
	KeyCommandSkillsShowUsage           Key = "command.skills.show_usage"
	KeyCommandSkillsNotFound            Key = "command.skills.not_found"
	KeyCommandSkillsToggleUsage         Key = "command.skills.toggle_usage"
	KeyCommandSkillsRefreshUsage        Key = "command.skills.refresh_usage"
	KeyCommandSkillsRefreshed           Key = "command.skills.refreshed"
	KeyCommandSkillsAllToggled          Key = "command.skills.all_toggled"
	KeyCommandSkillsAlreadyToggled      Key = "command.skills.already_toggled"
	KeyCommandSkillsToggled             Key = "command.skills.toggled"
	KeyCommandSkillsListHeader          Key = "command.skills.list_header"
	KeyCommandSkillsNone                Key = "command.skills.none"
	KeyCommandSkillsListEntry           Key = "command.skills.list_entry"
	KeyCommandSkillsListSummary         Key = "command.skills.list_summary"
	KeyCommandSkillsListSource          Key = "command.skills.list_source"
	KeyCommandSkillsListPath            Key = "command.skills.list_path"
	KeyCommandSkillsDetailHeader        Key = "command.skills.detail_header"
	KeyCommandSkillsDetailStatus        Key = "command.skills.detail_status"
	KeyCommandSkillsDetailSummary       Key = "command.skills.detail_summary"
	KeyCommandSkillsDetailSource        Key = "command.skills.detail_source"
	KeyCommandSkillsDetailPath          Key = "command.skills.detail_path"
	KeyCommandSkillsDetailDirectory     Key = "command.skills.detail_directory"
	KeyCommandSkillsDetailModelInvoke   Key = "command.skills.detail_model_invocation"
	KeyCommandSkillsDetailUserInvoke    Key = "command.skills.detail_user_invocation"
	KeyCommandSkillsDetailContext       Key = "command.skills.detail_context"
	KeyCommandSkillsDetailModel         Key = "command.skills.detail_model"
	KeyCommandSkillsDetailVersion       Key = "command.skills.detail_version"
	KeyCommandSkillsDetailTools         Key = "command.skills.detail_tools"
	KeyCommandSkillsDetailAliases       Key = "command.skills.detail_aliases"
	KeyCommandSkillsStatusEnabled       Key = "command.skills.status_enabled"
	KeyCommandSkillsStatusDisabled      Key = "command.skills.status_disabled"
	KeyCommandSkillsDisabledFrontmatter Key = "command.skills.disabled_frontmatter"
	KeyCommandSkillsInvocationBoth      Key = "command.skills.invocation_both"
	KeyCommandSkillsInvocationUser      Key = "command.skills.invocation_user"
	KeyCommandSkillsInvocationModel     Key = "command.skills.invocation_model"
	KeyCommandSkillsSessionCurrent      Key = "command.skills.session_current"
	KeyCommandSkillsSession             Key = "command.skills.session"
	KeyCommandSkillsNoneValue           Key = "command.skills.none_value"
	KeyCommandSkillsVirtualPath         Key = "command.skills.virtual_path"
	KeyCommandSkillsUsage               Key = "command.skills.usage"
	KeyCommandSkillsFullUsage           Key = "command.skills.full_usage"
	KeyCommandSkillsDescription         Key = "command.skills.description"
	KeyCommandSkillsSetUsage            Key = "command.skills.set_usage"
	KeyCommandSkillsResetUsage          Key = "command.skills.reset_usage"
	KeyCommandSkillsOperationFailed     Key = "command.skills.operation_failed"
	KeyCommandSkillsInvalidSelector     Key = "command.skills.invalid_selector"
	KeyCommandSkillsAmbiguous           Key = "command.skills.ambiguous"
	KeyCommandSkillsAmbiguousCandidate  Key = "command.skills.ambiguous_candidate"
	KeyCommandSkillsReadOnly            Key = "command.skills.read_only"
	KeyCommandSkillsSetResult           Key = "command.skills.set_result"
	KeyCommandSkillsResetResult         Key = "command.skills.reset_result"
	KeyCommandSkillsEffectiveState      Key = "command.skills.effective_state"
	KeyCommandSkillsReadOnlyManaged     Key = "command.skills.read_only_reason.managed"
	KeyCommandSkillsReadOnlyDenied      Key = "command.skills.read_only_reason.denied"
	KeyCommandSkillsCatalogRevision     Key = "command.skills.catalog_revision"
	KeyCommandSkillsListIdentity        Key = "command.skills.list_identity"
	KeyCommandSkillsListRevision        Key = "command.skills.list_revision"
	KeyCommandSkillsListPolicy          Key = "command.skills.list_policy"
	KeyCommandSkillsListShadowed        Key = "command.skills.list_shadowed"
	KeyCommandSkillsDetailIdentity      Key = "command.skills.detail_identity"
	KeyCommandSkillsDetailRevision      Key = "command.skills.detail_revision"
	KeyCommandSkillsDetailPolicy        Key = "command.skills.detail_policy"
	KeyCommandSkillsMutableYes          Key = "command.skills.mutable_yes"
	KeyCommandSkillsMutableNo           Key = "command.skills.mutable_no"
	KeyCommandSkillsToggleCommitted     Key = "command.skills.toggle_committed"
	KeyCommandSkillsToggleStale         Key = "command.skills.toggle_stale"
	KeyCommandSkillsToggleUnknown       Key = "command.skills.toggle_unknown"
	KeyCommandSkillsToggleReadOnly      Key = "command.skills.toggle_read_only"
	KeyCommandSkillsToggleSession       Key = "command.skills.toggle_session_override"
	KeyCommandSkillsTogglePersistFailed Key = "command.skills.toggle_persist_failed"
	KeyCommandSkillsToggleRolledBack    Key = "command.skills.toggle_rolled_back"
	KeyCommandSkillsToggleDegraded      Key = "command.skills.toggle_degraded"
	KeyCommandSkillsToggleRefreshFailed Key = "command.skills.toggle_refresh_failed"
)

func init() {
	for key, values := range map[Key][6]string{
		KeyCommandResumeStoreUnavailable: {"Session store not available.\n", "会话存储不可用。\n", "Sitzungsspeicher nicht verfügbar.\n", "セッションストアは利用できません。\n", "세션 저장소를 사용할 수 없습니다.\n", "Хранилище сеансов недоступно.\n"},
		KeyCommandResumeListError:        {"Error listing sessions: %v\n", "列出会话时出错：%v\n", "Fehler beim Auflisten der Sitzungen: %v\n", "セッション一覧の取得エラー: %v\n", "세션 목록 오류: %v\n", "Ошибка при выводе сеансов: %v\n"}, KeyCommandResumeNone: {"No saved sessions found.\n", "未找到已保存的会话。\n", "Keine gespeicherten Sitzungen gefunden.\n", "保存済みのセッションが見つかりません。\n", "저장된 세션을 찾을 수 없습니다.\n", "Сохраненные сеансы не найдены.\n"},
		KeyCommandResumeRecent: {"Recent sessions (use /resume <id-or-title> to load one):\n", "最近会话（使用 /resume <id-or-title> 加载）：\n", "Letzte Sitzungen (mit /resume <id-or-title> laden):\n", "最近のセッション（/resume <id-or-title> で読み込み）:\n", "최근 세션(/resume <id-or-title>로 불러오기):\n", "Недавние сеансы (загрузите через /resume <id-or-title>):\n"}, KeyCommandResumeEntry: {"%s%s  (%s, %d msgs)\n", "%s%s（%s，%d 条消息）\n", "%s%s  (%s, %d Nachr.)\n", "%s%s（%s、%d 件）\n", "%s%s  (%s, 메시지 %d개)\n", "%s%s  (%s, %d сообщ.)\n"},
		KeyCommandResumeSearchError: {"Error searching sessions: %v\n", "搜索会话时出错：%v\n", "Fehler beim Suchen von Sitzungen: %v\n", "セッション検索エラー: %v\n", "세션 검색 오류: %v\n", "Ошибка поиска сеансов: %v\n"}, KeyCommandResumeMultiple: {"Found %d sessions matching %q. Please refine your query.\n", "找到 %d 个与 %q 匹配的会话。请缩小查询范围。\n", "%d Sitzungen entsprechen %q. Bitte verfeinere die Suche.\n", "%d 件のセッションが %q に一致しました。検索を絞り込んでください。\n", "%d개의 세션이 %q와 일치합니다. 검색어를 구체화하세요.\n", "Найдено %d сеансов по запросу %q. Уточните запрос.\n"}, KeyCommandResumeLoadError: {"Error loading session %q: %v\n", "加载会话 %q 时出错：%v\n", "Fehler beim Laden der Sitzung %q: %v\n", "セッション %q の読み込みエラー: %v\n", "세션 %q을(를) 불러오는 중 오류: %v\n", "Ошибка загрузки сеанса %q: %v\n"}, KeyCommandResumeLoaded: {"Resumed session %s.\n", "已恢复会话 %s。\n", "Sitzung %s fortgesetzt.\n", "セッション %s を再開しました。\n", "세션 %s을(를) 재개했습니다.\n", "Сеанс %s возобновлен.\n"}, KeyCommandResumeLoadedMessages: {"Resumed session %s (%d messages).\n", "已恢复会话 %s（%d 条消息）。\n", "Sitzung %s fortgesetzt (%d Nachrichten).\n", "セッション %s を再開しました（%d 件のメッセージ）。\n", "세션 %s을(를) 재개했습니다(메시지 %d개).\n", "Сеанс %s возобновлен (%d сообщений).\n"},
		KeyCommandRenameStoreUnavailable: {"Session store not available.\n", "会话存储不可用。\n", "Sitzungsspeicher nicht verfügbar.\n", "セッションストアは利用できません。\n", "세션 저장소를 사용할 수 없습니다.\n", "Хранилище сеансов недоступно.\n"}, KeyCommandRenameGenerateFailed: {"Could not generate a session name yet. Usage: /rename <name>\n", "暂时无法生成会话名称。用法：/rename <name>\n", "Es konnte noch kein Sitzungsname erstellt werden. Verwendung: /rename <name>\n", "まだセッション名を生成できません。使い方: /rename <name>\n", "아직 세션 이름을 생성할 수 없습니다. 사용법: /rename <name>\n", "Пока не удалось создать имя сеанса. Использование: /rename <name>\n"}, KeyCommandRenameError: {"Error renaming session: %v\n", "重命名会话时出错：%v\n", "Fehler beim Umbenennen der Sitzung: %v\n", "セッション名の変更エラー: %v\n", "세션 이름 변경 오류: %v\n", "Ошибка переименования сеанса: %v\n"}, KeyCommandRenameSucceeded: {"Session renamed to: %s\n", "会话已重命名为：%s\n", "Sitzung umbenannt in: %s\n", "セッション名を変更しました: %s\n", "세션 이름을 변경했습니다: %s\n", "Сеанс переименован в: %s\n"},
		KeyCommandForkUsage: {"usage: /fork", "用法：/fork", "Verwendung: /fork", "使い方: /fork", "사용법: /fork", "Использование: /fork"}, KeyCommandForkPickerUnavailable: {"fork picker is not configured", "分支选择器尚未配置", "Fork-Auswahl ist nicht konfiguriert", "フォーク選択画面が設定されていません", "포크 선택기가 구성되지 않았습니다", "Выбор ветвления не настроен"},
		KeyCommandDiffGitMissing: {"git not found in PATH — cannot show diff.\n", "未在 PATH 中找到 git，无法显示差异。\n", "git wurde nicht im PATH gefunden — Diff kann nicht angezeigt werden.\n", "PATH に git が見つからないため差分を表示できません。\n", "PATH에서 git을 찾을 수 없어 diff를 표시할 수 없습니다.\n", "git не найден в PATH — невозможно показать diff.\n"}, KeyCommandDiffNotRepository: {"Not inside a git repository. Changes are tracked via git — please initialise a repo with `git init` to use /diff.\n", "当前不在 git 仓库中。变更由 git 跟踪；请使用 `git init` 初始化仓库后再使用 /diff。\n", "Nicht in einem Git-Repository. Änderungen werden über git verfolgt — bitte mit `git init` ein Repository initialisieren, um /diff zu nutzen.\n", "git リポジトリ内ではありません。変更は git で追跡されます。/diff を使うには `git init` で初期化してください。\n", "git 저장소 안이 아닙니다. 변경 사항은 git으로 추적됩니다. /diff를 사용하려면 `git init`으로 저장소를 초기화하세요.\n", "Вы не в репозитории git. Изменения отслеживаются через git — выполните `git init`, чтобы использовать /diff.\n"}, KeyCommandDiffClean: {"No changes — working tree is clean.\n", "没有变更，工作区是干净的。\n", "Keine Änderungen — Arbeitsbaum ist sauber.\n", "変更はありません。作業ツリーはクリーンです。\n", "변경 사항이 없습니다. 작업 트리가 깨끗합니다.\n", "Нет изменений — рабочее дерево чистое.\n"}, KeyCommandDiffSummary: {"Summary: ", "摘要：", "Zusammenfassung: ", "概要: ", "요약: ", "Сводка: "}, KeyCommandDiffUntracked: {"Untracked files:\n", "未跟踪文件：\n", "Nicht verfolgte Dateien:\n", "未追跡ファイル:\n", "추적되지 않은 파일:\n", "Неотслеживаемые файлы:\n"},
		KeyCommandReviewGitMissing: {"git not found in PATH — cannot show review diff.\n", "未在 PATH 中找到 git，无法显示审查差异。\n", "git wurde nicht im PATH gefunden — Review-Diff kann nicht angezeigt werden.\n", "PATH に git が見つからないためレビュー用差分を表示できません。\n", "PATH에서 git을 찾을 수 없어 리뷰 diff를 표시할 수 없습니다.\n", "git не найден в PATH — невозможно показать diff для ревью.\n"}, KeyCommandReviewNotRepository: {"Not inside a git repository.\n", "当前不在 git 仓库中。\n", "Nicht in einem Git-Repository.\n", "git リポジトリ内ではありません。\n", "git 저장소 안이 아닙니다.\n", "Вы не в репозитории git.\n"}, KeyCommandReviewNoStaged: {"No staged changes to review.\n", "没有已暂存的变更可供审查。\n", "Keine bereitgestellten Änderungen zum Review.\n", "レビューするステージ済み変更はありません。\n", "검토할 스테이지된 변경 사항이 없습니다.\n", "Нет подготовленных изменений для ревью.\n"}, KeyCommandReviewClean: {"No changes to review — working tree is clean.\n", "没有变更可供审查，工作区是干净的。\n", "Keine Änderungen zum Review — Arbeitsbaum ist sauber.\n", "レビューする変更はありません。作業ツリーはクリーンです。\n", "검토할 변경 사항이 없습니다. 작업 트리가 깨끗합니다.\n", "Нет изменений для ревью — рабочее дерево чистое.\n"}, KeyCommandReviewAllChanges: {"Unstaged + staged changes", "未暂存 + 已暂存变更", "Nicht bereitgestellte + bereitgestellte Änderungen", "未ステージ + ステージ済み変更", "스테이지 전 + 스테이지된 변경 사항", "Неподготовленные + подготовленные изменения"}, KeyCommandReviewStagedChanges: {"Staged changes", "已暂存变更", "Bereitgestellte Änderungen", "ステージ済み変更", "스테이지된 변경 사항", "Подготовленные изменения"},
		KeyCommandPasteNoImage: {"📋 No image found in clipboard.\n", "📋 剪贴板中未找到图片。\n", "📋 Kein Bild in der Zwischenablage gefunden.\n", "📋 クリップボードに画像がありません。\n", "📋 클립보드에서 이미지를 찾을 수 없습니다.\n", "📋 В буфере обмена нет изображения.\n"}, KeyCommandPasteConfirmUnavailable: {"(clipboard paste requires confirmation but no confirmer available)\n", "（粘贴剪贴板图片需要确认，但没有可用的确认器）\n", "(Einfügen aus der Zwischenablage erfordert Bestätigung, aber keine Bestätigung verfügbar)\n", "（クリップボードからの貼り付けには確認が必要ですが、確認手段がありません）\n", "(클립보드 붙여넣기에는 확인이 필요하지만 확인 수단이 없습니다)\n", "(Вставка из буфера требует подтверждения, но подтверждение недоступно)\n"}, KeyCommandPasteConfirm: {"📎 Clipboard image detected. Send to %s? [y/N] ", "📎 检测到剪贴板图片。发送到 %s？[y/N] ", "📎 Bild in Zwischenablage erkannt. An %s senden? [y/N] ", "📎 クリップボードの画像を検出しました。%s に送信しますか？ [y/N] ", "📎 클립보드 이미지를 감지했습니다. %s(으)로 보낼까요? [y/N] ", "📎 Обнаружено изображение в буфере. Отправить в %s? [y/N] "}, KeyCommandPasteCancelled: {"(clipboard paste cancelled)\n", "（已取消粘贴剪贴板图片）\n", "(Einfügen aus Zwischenablage abgebrochen)\n", "（クリップボードからの貼り付けをキャンセルしました）\n", "(클립보드 붙여넣기가 취소되었습니다)\n", "(Вставка из буфера отменена)\n"}, KeyCommandPasteReadError: {"Error reading clipboard: %v\n", "读取剪贴板时出错：%v\n", "Fehler beim Lesen der Zwischenablage: %v\n", "クリップボード読み取りエラー: %v\n", "클립보드 읽기 오류: %v\n", "Ошибка чтения буфера обмена: %v\n"}, KeyCommandPasteEmpty: {"📋 Clipboard image was empty.\n", "📋 剪贴板图片为空。\n", "📋 Bild in der Zwischenablage war leer.\n", "📋 クリップボードの画像は空でした。\n", "📋 클립보드 이미지가 비어 있습니다.\n", "📋 Изображение в буфере было пустым.\n"}, KeyCommandPasteReady: {"✅ Clipboard image ready — sending to %s…\n", "✅ 剪贴板图片已就绪，正在发送到 %s…\n", "✅ Bild aus Zwischenablage bereit — wird an %s gesendet…\n", "✅ クリップボード画像の準備完了 — %s に送信します…\n", "✅ 클립보드 이미지 준비 완료 — %s(으)로 전송합니다…\n", "✅ Изображение из буфера готово — отправка в %s…\n"},
		KeyCommandMemoryResolveError: {"Error resolving instruction file: %v\n", "解析指令文件时出错：%v\n", "Fehler beim Auflösen der Anweisungsdatei: %v\n", "指示ファイルの解決エラー: %v\n", "지침 파일 확인 오류: %v\n", "Ошибка определения файла инструкций: %v\n"}, KeyCommandMemoryCreated: {"No instruction file found — created a new one at %s\n", "未找到指令文件，已在 %s 创建新文件\n", "Keine Anweisungsdatei gefunden — neue Datei unter %s erstellt\n", "指示ファイルが見つからないため、%s に新規作成しました\n", "%s에 지침 파일을 새로 만들었습니다.\n", "Файл инструкций не найден — создан новый: %s\n"}, KeyCommandMemoryOpening: {"Opening memory file: %s\n", "正在打开记忆文件：%s\n", "Speicherdatei wird geöffnet: %s\n", "メモリファイルを開いています: %s\n", "메모리 파일을 엽니다: %s\n", "Открывается файл памяти: %s\n"}, KeyCommandMemoryEditorError: {"Error: %v\n", "错误：%v\n", "Fehler: %v\n", "エラー: %v\n", "오류: %v\n", "Ошибка: %v\n"}, KeyCommandMemoryEditorExited: {"Editor exited with error: %v\n", "编辑器异常退出：%v\n", "Editor wurde mit Fehler beendet: %v\n", "エディターがエラーで終了しました: %v\n", "편집기가 오류와 함께 종료되었습니다: %v\n", "Редактор завершился с ошибкой: %v\n"}, KeyCommandMemoryEditorHintSource: {"> Using %s. To change editor, set $EDITOR or $VISUAL environment variable.", "> 正在使用 %s。若要更改编辑器，请设置 $EDITOR 或 $VISUAL 环境变量。", "> Verwendet %s. Zum Ändern des Editors $EDITOR oder $VISUAL setzen.", "> %s を使用中です。エディターを変えるには $EDITOR または $VISUAL を設定してください。", "> %s을(를) 사용 중입니다. 편집기를 바꾸려면 $EDITOR 또는 $VISUAL 환경 변수를 설정하세요.", "> Используется %s. Чтобы сменить редактор, задайте $EDITOR или $VISUAL."}, KeyCommandMemoryEditorHint: {"> To use a different editor, set the $EDITOR or $VISUAL environment variable.", "> 若要使用其他编辑器，请设置 $EDITOR 或 $VISUAL 环境变量。", "> Um einen anderen Editor zu nutzen, $EDITOR oder $VISUAL setzen.", "> 別のエディターを使うには、$EDITOR または $VISUAL を設定してください。", "> 다른 편집기를 사용하려면 $EDITOR 또는 $VISUAL 환경 변수를 설정하세요.", "> Чтобы использовать другой редактор, задайте $EDITOR или $VISUAL."}, KeyCommandMemoryOpened: {"Opened memory file at %s\n\n%s\n", "已在 %s 打开记忆文件\n\n%s\n", "Speicherdatei unter %s geöffnet\n\n%s\n", "%s のメモリファイルを開きました\n\n%s\n", "%s에서 메모리 파일을 열었습니다\n\n%s\n", "Файл памяти открыт: %s\n\n%s\n"}, KeyCommandMemoryNoEditor: {"no editor found: set $EDITOR or $VISUAL, or install vim/nano", "未找到编辑器：请设置 $EDITOR 或 $VISUAL，或安装 vim/nano", "Kein Editor gefunden: $EDITOR oder $VISUAL setzen oder vim/nano installieren", "エディターが見つかりません: $EDITOR または $VISUAL を設定するか vim/nano をインストールしてください", "편집기를 찾을 수 없습니다: $EDITOR 또는 $VISUAL을 설정하거나 vim/nano를 설치하세요", "Редактор не найден: задайте $EDITOR или $VISUAL либо установите vim/nano"},
		KeyCommandSkillsUnavailable: {"skills manager is not configured", "技能管理器尚未配置", "Skill-Manager ist nicht konfiguriert", "スキルマネージャーが設定されていません", "스킬 관리자가 구성되지 않았습니다", "Менеджер навыков не настроен"}, KeyCommandSkillsShowUsage: {"Usage: /skills show <name>\n", "用法：/skills show <name>\n", "Verwendung: /skills show <name>\n", "使い方: /skills show <name>\n", "사용법: /skills show <name>\n", "Использование: /skills show <name>\n"}, KeyCommandSkillsNotFound: {"Skill %q not found. Run /skills list to inspect the catalog.\n", "未找到技能 %q。请运行 /skills list 查看目录。\n", "Skill %q nicht gefunden. Mit /skills list den Katalog anzeigen.\n", "スキル %q が見つかりません。/skills list でカタログを確認してください。\n", "스킬 %q을(를) 찾을 수 없습니다. /skills list로 카탈로그를 확인하세요.\n", "Навык %q не найден. Выполните /skills list для просмотра каталога.\n"}, KeyCommandSkillsToggleUsage: {"Usage: /skills %s <name|all>\n", "用法：/skills %s <name|all>\n", "Verwendung: /skills %s <name|all>\n", "使い方: /skills %s <name|all>\n", "사용법: /skills %s <name|all>\n", "Использование: /skills %s <name|all>\n"}, KeyCommandSkillsRefreshUsage: {"Usage: /skills refresh\n", "用法：/skills refresh\n", "Verwendung: /skills refresh\n", "使い方: /skills refresh\n", "사용법: /skills refresh\n", "Использование: /skills refresh\n"}, KeyCommandSkillsRefreshed: {"Refreshed the skill catalog.\n", "已刷新技能目录。\n", "Skill-Katalog aktualisiert.\n", "スキルカタログを更新しました。\n", "스킬 카탈로그를 새로 고쳤습니다.\n", "Каталог навыков обновлен.\n"}, KeyCommandSkillsAllToggled: {"%s %d skill(s) for %s. Changes are visible to the model on the next request; Skill tool enforcement is immediate.\n", "%s 了 %d 个技能（%s）。变更将在下次请求时对模型生效；Skill 工具限制立即生效。\n", "%s %d Skill(s) für %s. Änderungen sind beim nächsten Request für das Modell sichtbar; die Skill-Tool-Durchsetzung greift sofort.\n", "%s: %d 件のスキルを %s で変更しました。変更は次のリクエストでモデルに反映され、Skill ツールの適用は直ちに有効です。\n", "%s: 스킬 %d개를 %s에서 변경했습니다. 변경 사항은 다음 요청에서 모델에 반영되고 Skill 도구 제한은 즉시 적용됩니다.\n", "%s %d навыков для %s. Изменения станут видны модели в следующем запросе; ограничения инструмента Skill действуют сразу.\n"}, KeyCommandSkillsAlreadyToggled: {"Skill %q is already %s for %s.\n", "技能 %q 已是%s（%s）。\n", "Skill %q ist bereits %s für %s.\n", "スキル %q はすでに %s です（%s）。\n", "스킬 %q은(는) 이미 %s 상태입니다(%s).\n", "Навык %q уже %s для %s.\n"}, KeyCommandSkillsToggled: {"%s skill %q for %s. The model sees the availability delta on the next request; Skill tool enforcement is immediate.\n", "%s技能 %q（%s）。模型将在下次请求时看到可用性变化；Skill 工具限制立即生效。\n", "%s Skill %q für %s. Das Modell sieht die Verfügbarkeitsänderung beim nächsten Request; die Skill-Tool-Durchsetzung greift sofort.\n", "%s: スキル %q（%s）。モデルは次のリクエストで利用可否の変更を認識し、Skill ツールの適用は直ちに有効です。\n", "%s: 스킬 %q(%s). 모델은 다음 요청에서 가용성 변경을 확인하고 Skill 도구 제한은 즉시 적용됩니다.\n", "%s навык %q для %s. Модель увидит изменение доступности в следующем запросе; ограничения инструмента Skill действуют сразу.\n"},
		KeyCommandSkillsListHeader: {"Skills: %d discovered, %d enabled, %d disabled (%s)\n", "技能：发现 %d 个，已启用 %d 个，已禁用 %d 个（%s）\n", "Skills: %d gefunden, %d aktiviert, %d deaktiviert (%s)\n", "スキル: %d 件検出、%d 件有効、%d 件無効（%s）\n", "스킬: %d개 발견, %d개 활성화, %d개 비활성화(%s)\n", "Навыки: найдено %d, включено %d, выключено %d (%s)\n"}, KeyCommandSkillsNone: {"  No skills discovered. Run /skills refresh after installing one.\n", "  未发现技能。安装后请运行 /skills refresh。\n", "  Keine Skills gefunden. Nach der Installation /skills refresh ausführen.\n", "  スキルが見つかりません。インストール後に /skills refresh を実行してください。\n", "  스킬을 찾지 못했습니다. 설치 후 /skills refresh를 실행하세요.\n", "  Навыки не найдены. После установки выполните /skills refresh.\n"}, KeyCommandSkillsListEntry: {"  [%s] %s\n", "  [%s] %s\n", "  [%s] %s\n", "  [%s] %s\n", "  [%s] %s\n", "  [%s] %s\n"}, KeyCommandSkillsListSummary: {"    Summary: %s\n", "    摘要：%s\n", "    Zusammenfassung: %s\n", "    概要: %s\n", "    요약: %s\n", "    Сводка: %s\n"}, KeyCommandSkillsListSource: {"    Source: %s | Invocation: %s\n", "    来源：%s｜调用：%s\n", "    Quelle: %s | Aufruf: %s\n", "    提供元: %s｜呼び出し: %s\n", "    출처: %s | 호출: %s\n", "    Источник: %s | Вызов: %s\n"}, KeyCommandSkillsListPath: {"    Path: %s\n", "    路径：%s\n", "    Pfad: %s\n", "    パス: %s\n", "    경로: %s\n", "    Путь: %s\n"},
		KeyCommandSkillsDetailHeader: {"Skill: %s\n", "技能：%s\n", "Skill: %s\n", "スキル: %s\n", "스킬: %s\n", "Навык: %s\n"}, KeyCommandSkillsDetailStatus: {"  Status: %s (%s)\n", "  状态：%s（%s）\n", "  Status: %s (%s)\n", "  状態: %s（%s）\n", "  상태: %s(%s)\n", "  Статус: %s (%s)\n"}, KeyCommandSkillsDetailSummary: {"  Summary: %s\n", "  摘要：%s\n", "  Zusammenfassung: %s\n", "  概要: %s\n", "  요약: %s\n", "  Сводка: %s\n"}, KeyCommandSkillsDetailSource: {"  Source: %s\n", "  来源：%s\n", "  Quelle: %s\n", "  提供元: %s\n", "  출처: %s\n", "  Источник: %s\n"}, KeyCommandSkillsDetailPath: {"  Path: %s\n", "  路径：%s\n", "  Pfad: %s\n", "  パス: %s\n", "  경로: %s\n", "  Путь: %s\n"}, KeyCommandSkillsDetailDirectory: {"  Directory: %s\n", "  目录：%s\n", "  Verzeichnis: %s\n", "  ディレクトリ: %s\n", "  디렉터리: %s\n", "  Каталог: %s\n"}, KeyCommandSkillsDetailModelInvoke: {"  Model invocation: %s\n", "  模型调用：%s\n", "  Modellaufruf: %s\n", "  モデル呼び出し: %s\n", "  모델 호출: %s\n", "  Вызов моделью: %s\n"}, KeyCommandSkillsDetailUserInvoke: {"  User invocation: %s\n", "  用户调用：%s\n", "  Benutzeraufruf: %s\n", "  ユーザー呼び出し: %s\n", "  사용자 호출: %s\n", "  Вызов пользователем: %s\n"}, KeyCommandSkillsDetailContext: {"  Context: %s\n", "  上下文：%s\n", "  Kontext: %s\n", "  コンテキスト: %s\n", "  컨텍스트: %s\n", "  Контекст: %s\n"}, KeyCommandSkillsDetailModel: {"  Model override: %s\n", "  模型覆盖：%s\n", "  Modellüberschreibung: %s\n", "  モデル上書き: %s\n", "  모델 재정의: %s\n", "  Переопределение модели: %s\n"}, KeyCommandSkillsDetailVersion: {"  Version: %s\n", "  版本：%s\n", "  Version: %s\n", "  バージョン: %s\n", "  버전: %s\n", "  Версия: %s\n"}, KeyCommandSkillsDetailTools: {"  Allowed tools: %s\n", "  允许工具：%s\n", "  Erlaubte Tools: %s\n", "  許可ツール: %s\n", "  허용 도구: %s\n", "  Разрешенные инструменты: %s\n"}, KeyCommandSkillsDetailAliases: {"  Aliases: %s\n", "  别名：%s\n", "  Aliase: %s\n", "  エイリアス: %s\n", "  별칭: %s\n", "  Псевдонимы: %s\n"},
		KeyCommandSkillsStatusEnabled: {"enabled", "已启用", "aktiviert", "有効", "활성화됨", "включен"}, KeyCommandSkillsStatusDisabled: {"disabled", "已禁用", "deaktiviert", "無効", "비활성화됨", "выключен"}, KeyCommandSkillsDisabledFrontmatter: {"disabled by frontmatter", "已由 frontmatter 禁用", "durch Frontmatter deaktiviert", "frontmatter により無効", "frontmatter로 비활성화됨", "отключен frontmatter"}, KeyCommandSkillsInvocationBoth: {"model + user", "模型 + 用户", "Modell + Benutzer", "モデル + ユーザー", "모델 + 사용자", "модель + пользователь"}, KeyCommandSkillsInvocationUser: {"user only (frontmatter)", "仅用户（frontmatter）", "nur Benutzer (Frontmatter)", "ユーザーのみ（frontmatter）", "사용자만(frontmatter)", "только пользователь (frontmatter)"}, KeyCommandSkillsInvocationModel: {"model only (frontmatter)", "仅模型（frontmatter）", "モデルのみ（frontmatter）", "モデルのみ（frontmatter）", "모델만(frontmatter)", "только модель (frontmatter)"}, KeyCommandSkillsSessionCurrent: {"current runtime", "当前运行时", "aktuelle Laufzeit", "現在のランタイム", "현재 런타임", "текущая среда выполнения"}, KeyCommandSkillsSession: {"session %s", "会话 %s", "Sitzung %s", "セッション %s", "세션 %s", "сеанс %s"}, KeyCommandSkillsNoneValue: {"(none)", "（无）", "(keine)", "（なし）", "(없음)", "(нет)"}, KeyCommandSkillsVirtualPath: {"(virtual)", "（虚拟）", "(virtuell)", "（仮想）", "(가상)", "(виртуальный)"}, KeyCommandSkillsUsage: {"Usage:\n  /skills [list]\n  /skills show <name>\n  /skills enable <name|all>\n  /skills disable <name|all>\n  /skills refresh\n", "用法：\n  /skills [list]\n  /skills show <name>\n  /skills enable <name|all>\n  /skills disable <name|all>\n  /skills refresh\n", "Verwendung:\n  /skills [list]\n  /skills show <name>\n  /skills enable <name|all>\n  /skills disable <name|all>\n  /skills refresh\n", "使い方:\n  /skills [list]\n  /skills show <name>\n  /skills enable <name|all>\n  /skills disable <name|all>\n  /skills refresh\n", "사용법:\n  /skills [list]\n  /skills show <name>\n  /skills enable <name|all>\n  /skills disable <name|all>\n  /skills refresh\n", "Использование:\n  /skills [list]\n  /skills show <name>\n  /skills enable <name|all>\n  /skills disable <name|all>\n  /skills refresh\n"},
		KeyCommandSkillsFullUsage:           {"Usage:\n  /skills [list]\n  /skills show <selector>\n  /skills set <selector> <auto|name-only|manual-only|off> --scope <session|project|user>\n  /skills reset <selector> --scope <session|project|user>\n  /skills enable <selector|all>\n  /skills disable <selector|all>\n  /skills refresh\n", "用法：\n  /skills [list]\n  /skills show <selector>\n  /skills set <selector> <auto|name-only|manual-only|off> --scope <session|project|user>\n  /skills reset <selector> --scope <session|project|user>\n  /skills enable <selector|all>\n  /skills disable <selector|all>\n  /skills refresh\n", "Verwendung:\n  /skills [list]\n  /skills show <selector>\n  /skills set <selector> <auto|name-only|manual-only|off> --scope <session|project|user>\n  /skills reset <selector> --scope <session|project|user>\n  /skills enable <selector|all>\n  /skills disable <selector|all>\n  /skills refresh\n", "使い方:\n  /skills [list]\n  /skills show <selector>\n  /skills set <selector> <auto|name-only|manual-only|off> --scope <session|project|user>\n  /skills reset <selector> --scope <session|project|user>\n  /skills enable <selector|all>\n  /skills disable <selector|all>\n  /skills refresh\n", "사용법:\n  /skills [list]\n  /skills show <selector>\n  /skills set <selector> <auto|name-only|manual-only|off> --scope <session|project|user>\n  /skills reset <selector> --scope <session|project|user>\n  /skills enable <selector|all>\n  /skills disable <selector|all>\n  /skills refresh\n", "Использование:\n  /skills [list]\n  /skills show <selector>\n  /skills set <selector> <auto|name-only|manual-only|off> --scope <session|project|user>\n  /skills reset <selector> --scope <session|project|user>\n  /skills enable <selector|all>\n  /skills disable <selector|all>\n  /skills refresh\n"},
		KeyCommandSkillsSetUsage:            {"Usage: /skills set <selector> <auto|name-only|manual-only|off> --scope <session|project|user>\n", "用法：/skills set <selector> <auto|name-only|manual-only|off> --scope <session|project|user>\n", "Verwendung: /skills set <selector> <auto|name-only|manual-only|off> --scope <session|project|user>\n", "使い方: /skills set <selector> <auto|name-only|manual-only|off> --scope <session|project|user>\n", "사용법: /skills set <selector> <auto|name-only|manual-only|off> --scope <session|project|user>\n", "Использование: /skills set <selector> <auto|name-only|manual-only|off> --scope <session|project|user>\n"},
		KeyCommandSkillsResetUsage:          {"Usage: /skills reset <selector> --scope <session|project|user>\n", "用法：/skills reset <selector> --scope <session|project|user>\n", "Verwendung: /skills reset <selector> --scope <session|project|user>\n", "使い方: /skills reset <selector> --scope <session|project|user>\n", "사용법: /skills reset <selector> --scope <session|project|user>\n", "Использование: /skills reset <selector> --scope <session|project|user>\n"},
		KeyCommandSkillsOperationFailed:     {"Skill operation failed: %v\n", "技能操作失败：%v\n", "Skill-Aktion fehlgeschlagen: %v\n", "スキル操作に失敗しました: %v\n", "스킬 작업 실패: %v\n", "Операция с навыком завершилась ошибкой: %v\n"},
		KeyCommandSkillsInvalidSelector:     {"Invalid stable skill selector %q. Run /skills list and use the complete skill ID.\n", "稳定技能选择器 %q 无效。请运行 /skills list 并使用完整技能 ID。\n", "Ungültiger stabiler Skill-Selektor %q. Mit /skills list die vollständige Skill-ID ermitteln.\n", "安定スキルセレクター %q は無効です。/skills list で完全なスキル ID を確認してください。\n", "안정적인 스킬 선택자 %q이(가) 올바르지 않습니다. /skills list에서 전체 스킬 ID를 확인하세요.\n", "Недопустимый стабильный селектор навыка %q. Выполните /skills list и укажите полный ID навыка.\n"},
		KeyCommandSkillsAmbiguous:           {"Skill name %q is ambiguous. Use one of these stable IDs:\n", "技能名称 %q 存在歧义。请使用以下稳定 ID 之一：\n", "Der Skill-Name %q ist mehrdeutig. Eine dieser stabilen IDs verwenden:\n", "スキル名 %q は一意ではありません。次の安定 ID のいずれかを使用してください:\n", "스킬 이름 %q이(가) 모호합니다. 다음 안정적인 ID 중 하나를 사용하세요:\n", "Имя навыка %q неоднозначно. Используйте один из стабильных ID:\n"},
		KeyCommandSkillsAmbiguousCandidate:  {"  %s (source: %s, locator: %s)\n", "  %s（来源：%s，定位符：%s）\n", "  %s (Quelle: %s, Locator: %s)\n", "  %s（提供元: %s、ロケーター: %s）\n", "  %s(출처: %s, 위치: %s)\n", "  %s (источник: %s, расположение: %s)\n"},
		KeyCommandSkillsReadOnly:            {"Skill %q (%s) is read-only: %s.\n", "技能 %q（%s）为只读：%s。\n", "Skill %q (%s) ist schreibgeschützt: %s.\n", "スキル %q（%s）は読み取り専用です: %s。\n", "스킬 %q(%s)은(는) 읽기 전용입니다: %s.\n", "Навык %q (%s) доступен только для чтения: %s.\n"},
		KeyCommandSkillsSetResult:           {"Set skill %q (%s) to %s at %s scope. Effective visibility: %s (source: %s).\n", "已将技能 %q（%s）设为 %s（作用域：%s）。有效可见性：%s（来源：%s）。\n", "Skill %q (%s) auf %s im Bereich %s gesetzt. Effektive Sichtbarkeit: %s (Quelle: %s).\n", "スキル %q（%s）を %s に設定しました（スコープ: %s）。有効な表示範囲: %s（ソース: %s）。\n", "스킬 %q(%s)을(를) %s(으)로 설정했습니다(범위: %s). 유효 표시 범위: %s(출처: %s).\n", "Для навыка %q (%s) задано %s в области %s. Итоговая видимость: %s (источник: %s).\n"},
		KeyCommandSkillsResetResult:         {"Reset skill %q (%s) at %s scope. Effective visibility: %s (source: %s).\n", "已重置技能 %q（%s）的 %s 作用域。有效可见性：%s（来源：%s）。\n", "Skill %q (%s) im Bereich %s zurückgesetzt. Effektive Sichtbarkeit: %s (Quelle: %s).\n", "スキル %q（%s）の %s スコープをリセットしました。有効な表示範囲: %s（ソース: %s）。\n", "스킬 %q(%s)의 %s 범위를 재설정했습니다. 유효 표시 범위: %s(출처: %s).\n", "Для навыка %q (%s) сброшена область %s. Итоговая видимость: %s (источник: %s).\n"},
		KeyCommandSkillsCatalogRevision:     {"Catalog revision: %d\n", "目录修订：%d\n", "Katalogrevision: %d\n", "カタログリビジョン: %d\n", "카탈로그 리비전: %d\n", "Ревизия каталога: %d\n"},
		KeyCommandSkillsListIdentity:        {"    ID: %s | Source: %s | Locator: %s\n", "    ID：%s｜来源：%s｜定位符：%s\n", "    ID: %s | Quelle: %s | Locator: %s\n", "    ID: %s｜提供元: %s｜ロケーター: %s\n", "    ID: %s | 출처: %s | 위치: %s\n", "    ID: %s | Источник: %s | Расположение: %s\n"},
		KeyCommandSkillsListRevision:        {"    Digest: %s | Skill revision: %d\n", "    摘要值：%s｜技能修订：%d\n", "    Digest: %s | Skill-Revision: %d\n", "    ダイジェスト: %s｜スキルリビジョン: %d\n", "    다이제스트: %s | 스킬 리비전: %d\n", "    Дайджест: %s | Ревизия навыка: %d\n"},
		KeyCommandSkillsListPolicy:          {"    Visibility: %s | State source: %s | Mutable: %s | Read-only reason: %s\n", "    可见性：%s｜状态来源：%s｜可修改：%s｜只读原因：%s\n", "    Sichtbarkeit: %s | Statusquelle: %s | Änderbar: %s | Schreibschutzgrund: %s\n", "    表示範囲: %s｜状態ソース: %s｜変更可能: %s｜読み取り専用の理由: %s\n", "    표시 범위: %s | 상태 출처: %s | 변경 가능: %s | 읽기 전용 사유: %s\n", "    Видимость: %s | Источник состояния: %s | Можно изменить: %s | Причина только для чтения: %s\n"},
		KeyCommandSkillsListShadowed:        {"    Shadowed by: %s\n", "    被以下技能遮蔽：%s\n", "    Überschattet durch: %s\n", "    次のスキルにより非優先: %s\n", "    다음 스킬에 의해 가려짐: %s\n", "    Перекрыт навыком: %s\n"},
		KeyCommandSkillsDetailIdentity:      {"  ID: %s | Source: %s | Locator: %s\n", "  ID：%s｜来源：%s｜定位符：%s\n", "  ID: %s | Quelle: %s | Locator: %s\n", "  ID: %s｜提供元: %s｜ロケーター: %s\n", "  ID: %s | 출처: %s | 위치: %s\n", "  ID: %s | Источник: %s | Расположение: %s\n"},
		KeyCommandSkillsDetailRevision:      {"  Digest: %s | Skill revision: %d | Catalog revision: %d\n", "  摘要值：%s｜技能修订：%d｜目录修订：%d\n", "  Digest: %s | Skill-Revision: %d | Katalogrevision: %d\n", "  ダイジェスト: %s｜スキルリビジョン: %d｜カタログリビジョン: %d\n", "  다이제스트: %s | 스킬 리비전: %d | 카탈로그 리비전: %d\n", "  Дайджест: %s | Ревизия навыка: %d | Ревизия каталога: %d\n"},
		KeyCommandSkillsDetailPolicy:        {"  Visibility: %s | State source: %s | Mutable: %s | Read-only reason: %s\n", "  可见性：%s｜状态来源：%s｜可修改：%s｜只读原因：%s\n", "  Sichtbarkeit: %s | Statusquelle: %s | Änderbar: %s | Schreibschutzgrund: %s\n", "  表示範囲: %s｜状態ソース: %s｜変更可能: %s｜読み取り専用の理由: %s\n", "  표시 범위: %s | 상태 출처: %s | 변경 가능: %s | 읽기 전용 사유: %s\n", "  Видимость: %s | Источник состояния: %s | Можно изменить: %s | Причина только для чтения: %s\n"},
		KeyCommandSkillsMutableYes:          {"yes", "是", "ja", "はい", "예", "да"},
		KeyCommandSkillsMutableNo:           {"no", "否", "nein", "いいえ", "아니요", "нет"},
		KeyCommandSkillsToggleCommitted:     {"Skill %q (%s) now has %s visibility at project scope.\n", "技能 %q（%s）在 project 作用域的可见性现为 %s。\n", "Skill %q (%s) hat im Bereich project jetzt die Sichtbarkeit %s.\n", "スキル %q（%s）の project スコープでの表示範囲が %s になりました。\n", "스킬 %q(%s)의 project 범위 표시 상태가 %s(으)로 변경되었습니다.\n", "Для навыка %q (%s) в области project теперь установлена видимость %s.\n"},
		KeyCommandSkillsToggleStale:         {"The skill catalog changed before %s could be updated. The authoritative list has been refreshed; retry with the current row.\n", "%s 更新前技能目录已发生变化。已刷新权威列表，请在当前条目上重试。\n", "Der Skill-Katalog wurde geändert, bevor %s aktualisiert werden konnte. Die maßgebliche Liste wurde aktualisiert; mit dem aktuellen Eintrag erneut versuchen.\n", "%s の更新前にスキルカタログが変更されました。最新の一覧に更新したため、現在の行でもう一度実行してください。\n", "%s을(를) 변경하기 전에 스킬 카탈로그가 바뀌었습니다. 최신 목록으로 새로 고쳤으니 현재 행에서 다시 시도하세요.\n", "Каталог навыков изменился до обновления %s. Актуальный список обновлен; повторите действие с текущей строкой.\n"},
		KeyCommandSkillsToggleUnknown:       {"Skill %s no longer exists. The authoritative list has been refreshed.\n", "技能 %s 已不存在。已刷新权威列表。\n", "Skill %s ist nicht mehr vorhanden. Die maßgebliche Liste wurde aktualisiert.\n", "スキル %s は存在しません。最新の一覧に更新しました。\n", "스킬 %s이(가) 더 이상 존재하지 않습니다. 최신 목록으로 새로 고쳤습니다.\n", "Навык %s больше не существует. Актуальный список обновлен.\n"},
		KeyCommandSkillsToggleReadOnly:      {"Skill %q (%s) is read-only and cannot be changed here: %s.\n", "技能 %q（%s）为只读，无法在此更改：%s。\n", "Skill %q (%s) ist schreibgeschützt und kann hier nicht geändert werden: %s.\n", "スキル %q（%s）は読み取り専用のため、ここでは変更できません: %s。\n", "스킬 %q(%s)은(는) 읽기 전용이므로 여기서 변경할 수 없습니다: %s.\n", "Навык %q (%s) доступен только для чтения и не может быть изменен здесь: %s.\n"},
		KeyCommandSkillsToggleSession:       {"Skill %q (%s) has a session override. Clear it with /skills reset %s --scope session before changing the project setting.\n", "技能 %q（%s）存在 session 覆盖。更改 project 设置前，请先运行 /skills reset %s --scope session 清除它。\n", "Skill %q (%s) hat eine session-Überschreibung. Vor dem Ändern der project-Einstellung mit /skills reset %s --scope session zurücksetzen.\n", "スキル %q（%s）には session オーバーライドがあります。project 設定を変更する前に /skills reset %s --scope session で解除してください。\n", "스킬 %q(%s)에 session 재정의가 있습니다. project 설정을 변경하기 전에 /skills reset %s --scope session으로 해제하세요.\n", "Для навыка %q (%s) задано переопределение session. Перед изменением project выполните /skills reset %s --scope session.\n"},
		KeyCommandSkillsTogglePersistFailed: {"The project setting for skill %q (%s) could not be saved. Live state was not changed.\n", "无法保存技能 %q（%s）的 project 设置。实时状态未发生变化。\n", "Die project-Einstellung für Skill %q (%s) konnte nicht gespeichert werden. Der Live-Status wurde nicht geändert.\n", "スキル %q（%s）の project 設定を保存できませんでした。ライブ状態は変更されていません。\n", "스킬 %q(%s)의 project 설정을 저장하지 못했습니다. 실시간 상태는 변경되지 않았습니다.\n", "Не удалось сохранить настройку project для навыка %q (%s). Текущее состояние не изменено.\n"},
		KeyCommandSkillsToggleRolledBack:    {"Skill %q (%s) could not be applied live. The project setting was rolled back.\n", "技能 %q（%s）无法实时应用，project 设置已回滚。\n", "Skill %q (%s) konnte nicht live angewendet werden. Die project-Einstellung wurde zurückgesetzt.\n", "スキル %q（%s）をライブ状態に適用できなかったため、project 設定をロールバックしました。\n", "스킬 %q(%s)을(를) 실시간 상태에 적용하지 못해 project 설정을 롤백했습니다.\n", "Не удалось применить навык %q (%s) в текущем состоянии. Настройка project отменена.\n"},
		KeyCommandSkillsToggleDegraded:      {"Skill %q (%s) could not be applied live and the project rollback also failed. The authoritative state was refreshed; inspect it before retrying.\n", "技能 %q（%s）无法实时应用，且 project 回滚也失败。已刷新权威状态，请检查后再重试。\n", "Skill %q (%s) konnte nicht live angewendet werden, und auch das project-Rollback schlug fehl. Der maßgebliche Status wurde aktualisiert; vor einem neuen Versuch prüfen.\n", "スキル %q（%s）をライブ状態に適用できず、project のロールバックにも失敗しました。最新の状態に更新したため、確認してから再試行してください。\n", "스킬 %q(%s)을(를) 실시간 상태에 적용하지 못했고 project 롤백도 실패했습니다. 최신 상태로 새로 고쳤으니 확인 후 다시 시도하세요.\n", "Не удалось применить навык %q (%s), а откат project также завершился ошибкой. Актуальное состояние обновлено; проверьте его перед повтором.\n"},
		KeyCommandSkillsToggleRefreshFailed: {"The state of skill %q (%s) is uncertain because the authoritative refresh failed. Close the manager and run /skills refresh before retrying.\n", "由于权威刷新失败，技能 %q（%s）的状态不确定。请关闭管理器并运行 /skills refresh 后再重试。\n", "Der Status von Skill %q (%s) ist unklar, da die maßgebliche Aktualisierung fehlgeschlagen ist. Den Manager schließen und vor einem neuen Versuch /skills refresh ausführen.\n", "最新状態の更新に失敗したため、スキル %q（%s）の状態は不明です。管理画面を閉じ、/skills refresh を実行してから再試行してください。\n", "최신 상태 새로 고침에 실패하여 스킬 %q(%s)의 상태를 확인할 수 없습니다. 관리 화면을 닫고 /skills refresh를 실행한 뒤 다시 시도하세요.\n", "Состояние навыка %q (%s) неизвестно, так как обновление актуальных данных завершилось ошибкой. Закройте окно управления и выполните /skills refresh перед повтором.\n"},
	} {
		semanticTranslations[key] = commandSession(values[0], values[1], values[2], values[3], values[4], values[5])
	}

	semanticTranslations[KeyCommandSkillsEffectiveState] = commandSession(
		"Effective visibility remains %s (source: %s).\n",
		"有效可见性保持为 %s（来源：%s）。\n",
		"Die effektive Sichtbarkeit bleibt %s (Quelle: %s).\n",
		"有効な表示範囲は %s のままです（ソース: %s）。\n",
		"유효 표시 범위는 %s 상태로 유지됩니다(출처: %s).\n",
		"Итоговая видимость остается %s (источник: %s).\n",
	)
	semanticTranslations[KeyCommandSkillsReadOnlyManaged] = commandSession(
		"managed policy owns this setting",
		"此设置由托管策略控制",
		"diese Einstellung wird von einer verwalteten Richtlinie vorgegeben",
		"この設定は管理ポリシーによって制御されています",
		"이 설정은 관리된 정책에서 제어합니다",
		"эта настройка задана управляемой политикой",
	)
	semanticTranslations[KeyCommandSkillsReadOnlyDenied] = commandSession(
		"managed policy blocks this skill",
		"托管策略已禁用此技能",
		"eine verwaltete Richtlinie blockiert diesen Skill",
		"管理ポリシーによってこのスキルは禁止されています",
		"관리된 정책에서 이 스킬을 차단했습니다",
		"управляемая политика блокирует этот навык",
	)
}

func commandSession(en, zh, de, ja, ko, ru string) map[Language]string {
	return map[Language]string{LangEN: en, LangZH: zh, LangDE: de, LangJA: ja, LangKO: ko, LangRU: ru}
}
