package tools

import (
	"bytes"
	"context"
	"encoding/base64"
	"fmt"
	"io"
	"math"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"sort"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/agent-dance/luban/i18n"
	"github.com/agent-dance/luban/types"
)

const (
	pdfInfoTimeout   = 20 * time.Second
	pdfRenderTimeout = 120 * time.Second
)

// PDFErrorReason mirrors the structured failure reasons in the TS PDF helper.
// Read still returns tool-level error text, while callers can inspect the
// reason without parsing that text.
type PDFErrorReason string

const (
	PDFErrorEmpty             PDFErrorReason = "empty"
	PDFErrorTooLarge          PDFErrorReason = "too_large"
	PDFErrorPasswordProtected PDFErrorReason = "password_protected"
	PDFErrorCorrupted         PDFErrorReason = "corrupted"
	PDFErrorUnknown           PDFErrorReason = "unknown"
	PDFErrorUnavailable       PDFErrorReason = "unavailable"
)

type PDFError struct {
	Reason  PDFErrorReason
	Message string
	display error
	cause   error
}

func (e *PDFError) Error() string {
	if e == nil {
		return ""
	}
	if e.display != nil {
		return e.display.Error()
	}
	return e.Message
}

func (e *PDFError) Unwrap() error {
	if e == nil {
		return nil
	}
	return e.cause
}

func newPDFError(reason PDFErrorReason, key i18n.Key, args ...any) error {
	display := i18n.NewError(key, args...)
	return &PDFError{Reason: reason, Message: display.Error(), display: display}
}

func wrapPDFError(reason PDFErrorReason, key i18n.Key, cause error, args ...any) error {
	display := i18n.WrapError(key, cause, args...)
	return &PDFError{Reason: reason, Message: display.Error(), display: display, cause: cause}
}

// pdfErrorWithCause preserves a renderer or subprocess cause without adding
// it to stable user-facing copy. Raw output that belongs in the message must
// be passed separately as a semantic-key argument.
func pdfErrorWithCause(reason PDFErrorReason, key i18n.Key, cause error, args ...any) error {
	display := i18n.NewError(key, args...)
	return &PDFError{Reason: reason, Message: display.Error(), display: display, cause: cause}
}

var (
	pdfInfoPageCountPattern = regexp.MustCompile(`(?m)^Pages:\s+(\d+)\s*$`)
	swiftPDFRendererOnce    sync.Once
	swiftPDFRendererPath    string
	swiftPDFRendererErr     error
)

func getPDFPageCount(filePath string) (int, bool) {
	return getPDFPageCountWithPDFInfo(filePath)
}

// getPDFPageCountStrict mirrors getPDFPageCount but without the byte-pattern
// fallback. Used by code paths that must distinguish "page count detected by
// a real renderer" from "page count derived from a heuristic". Open-ended
// page-range resolution stays strict so the caller fails closed (rejecting
// the over-limit range) when no PDF renderer is available, matching the
// pre-byte-fallback behaviour relied on by long-standing tests.
func getPDFPageCountStrict(filePath string) (int, bool) {
	return getPDFPageCountWithPDFInfo(filePath)
}

// getPDFPageCountFromBytes is a best-effort fallback that scans the raw PDF
// bytes for `/Count N` after the root /Pages object. Works on a wide range
// of well-formed PDFs (including the test fixtures generated by writeTestPDF)
// when neither pdfinfo nor the Swift renderer is available — most relevant
// on Windows CI runners.
func getPDFPageCountFromBytes(filePath string) (int, bool) {
	data, err := os.ReadFile(filePath)
	if err != nil {
		return 0, false
	}
	if !bytes.HasPrefix(data, []byte("%PDF-")) {
		return 0, false
	}
	// Look for the highest-page /Count occurrence in /Pages-typed objects.
	// PDFs may contain nested page trees; the root Pages object is the one
	// we care about, and its /Count is the largest. Picking the maximum
	// across all matches mirrors the standard fallback used by pdf.js.
	pat := regexp.MustCompile(`/Type\s*/Pages[^>]*?/Count\s+(\d+)|/Count\s+(\d+)[^>]*?/Type\s*/Pages`)
	max := 0
	for _, m := range pat.FindAllSubmatch(data, -1) {
		for _, group := range m[1:] {
			if len(group) == 0 {
				continue
			}
			if n, err := strconv.Atoi(string(group)); err == nil && n > max {
				max = n
			}
		}
	}
	if max <= 0 {
		return 0, false
	}
	return max, true
}

func pdfPageExtractionAvailable() bool {
	return hasPDFToPPM()
}

func readPDFFile(filePath string) ([]byte, int64, error) {
	info, err := os.Stat(filePath)
	if err != nil {
		return nil, 0, wrapPDFError(PDFErrorUnknown, i18n.KeyToolPDFHelperReadFileFailed, err)
	}
	if info.Size() == 0 {
		return nil, 0, newPDFError(PDFErrorEmpty, i18n.KeyToolPDFHelperFileEmpty, filePath)
	}
	if info.Size() > pdfTargetRawSize {
		return nil, 0, newPDFError(PDFErrorTooLarge, i18n.KeyToolPDFHelperFileTooLarge, formatReadSize(pdfTargetRawSize))
	}

	file, err := os.Open(filePath)
	if err != nil {
		return nil, 0, wrapPDFError(PDFErrorUnknown, i18n.KeyToolPDFHelperReadFileFailed, err)
	}
	defer file.Close()

	header := make([]byte, 5)
	n, err := io.ReadFull(file, header)
	if err != nil && err != io.ErrUnexpectedEOF && err != io.EOF {
		return nil, 0, wrapPDFError(PDFErrorUnknown, i18n.KeyToolPDFHelperReadFileFailed, err)
	}
	if !bytes.Equal(header[:n], []byte("%PDF-")) {
		return nil, 0, newPDFError(PDFErrorCorrupted, i18n.KeyToolPDFHelperInvalidHeader, filePath)
	}

	data, err := os.ReadFile(filePath)
	if err != nil {
		return nil, 0, wrapPDFError(PDFErrorUnknown, i18n.KeyToolPDFHelperReadFileFailed, err)
	}
	return data, info.Size(), nil
}

type pdfPageExtraction struct {
	Images       []types.ImageBlock
	Count        int
	OriginalSize int64
	OutputDir    string
}

func extractPDFPageImages(filePath string, firstPage, lastPage int, toolResultsDir string) (result pdfPageExtraction, err error) {
	info, err := os.Stat(filePath)
	if err != nil {
		return result, wrapPDFError(PDFErrorUnknown, i18n.KeyToolPDFHelperReadFileFailed, err)
	}
	if info.Size() == 0 {
		return result, newPDFError(PDFErrorEmpty, i18n.KeyToolPDFHelperFileEmpty, filePath)
	}
	if info.Size() > pdfMaxExtractSize {
		return result, newPDFError(
			PDFErrorTooLarge,
			i18n.KeyToolPDFHelperExtractionFileTooLarge,
			formatReadSize(pdfMaxExtractSize),
		)
	}
	result.OriginalSize = info.Size()

	// Strict %PDF- magic byte check before invoking the renderer
	// subprocess. Mirrors TS pdf.ts which rejects HTML-as-PDF / ZIP-as-PDF
	// poisoning with a clear error rather than the opaque "corrupt"
	// message pdftoppm produces. See fr-pdf-magic-byte-strict.
	if err := verifyPDFMagicHeader(filePath); err != nil {
		return result, err
	}
	if !hasPDFToPPM() {
		return result, newPDFError(PDFErrorUnavailable, i18n.KeyToolPDFHelperRendererUnavailable)
	}
	if strings.TrimSpace(toolResultsDir) == "" {
		toolResultsDir = filepath.Join(os.TempDir(), "claude-code-go", "tool-results")
	}
	if err := os.MkdirAll(toolResultsDir, 0o755); err != nil {
		return result, i18n.WrapError(i18n.KeyToolPDFHelperCreateResultsDirectory, err)
	}
	dir, err := os.MkdirTemp(toolResultsDir, "pdf-*")
	if err != nil {
		return result, i18n.WrapError(i18n.KeyToolPDFHelperCreateExtractionDirectory, err)
	}
	result.OutputDir = dir
	cleanup := true
	defer func() {
		if cleanup {
			_ = os.RemoveAll(dir)
			result.OutputDir = ""
		}
	}()

	if err := extractPDFPagesWithPDFToPPM(filePath, dir, firstPage, lastPage); err != nil {
		return result, err
	}

	entries, err := os.ReadDir(dir)
	if err != nil {
		return result, i18n.WrapError(i18n.KeyToolPDFHelperReadExtractionOutput, err)
	}

	imageNames := make([]string, 0, len(entries))
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := entry.Name()
		if strings.HasSuffix(strings.ToLower(name), ".jpg") {
			imageNames = append(imageNames, name)
		}
	}
	sort.Strings(imageNames)
	if len(imageNames) == 0 {
		return result, i18n.NewError(i18n.KeyToolPDFHelperNoOutputPages)
	}

	images := make([]types.ImageBlock, 0, len(imageNames))
	for _, name := range imageNames {
		data, err := os.ReadFile(filepath.Join(dir, name))
		if err != nil {
			return result, i18n.WrapError(i18n.KeyToolPDFHelperReadExtractedPageImage, err)
		}
		images = append(images, types.ImageBlock{
			Type: types.ContentTypeImage,
			Source: &types.ImageSource{
				Type:      "base64",
				MediaType: "image/jpeg",
				Data:      encodeBase64(data),
			},
		})
	}

	result.Images = images
	result.Count = len(images)
	cleanup = false
	return result, nil
}

func hasPDFToPPM() bool {
	pdftoppmAvailableOnce.Do(func() {
		_, err := exec.LookPath("pdftoppm")
		pdftoppmAvailableCache = err == nil
	})
	return pdftoppmAvailableCache
}

// pdftoppmAvailableOnce caches the LookPath result for the process
// lifetime. Mirrors TS pdftoppmAvailable which is also memoised. Calling
// LookPath on every PDF read is wasteful in long-lived sessions.
var (
	pdftoppmAvailableOnce  sync.Once
	pdftoppmAvailableCache bool
)

// verifyPDFMagicHeader reads the first 5 bytes and confirms they match
// the PDF magic prefix "%PDF-". Used by paths that bypass readPDFFile
// (e.g. extractPDFPageImages) so non-PDF inputs are rejected with a clear
// message before any renderer subprocess is spawned. Mirrors TS pdf.ts.
func verifyPDFMagicHeader(filePath string) error {
	f, err := os.Open(filePath)
	if err != nil {
		return wrapPDFError(PDFErrorUnknown, i18n.KeyToolPDFHelperReadFileFailed, err)
	}
	defer f.Close()
	header := make([]byte, 5)
	n, err := io.ReadFull(f, header)
	if err != nil && err != io.ErrUnexpectedEOF && err != io.EOF {
		return wrapPDFError(PDFErrorUnknown, i18n.KeyToolPDFHelperReadFileFailed, err)
	}
	if !bytes.Equal(header[:n], []byte("%PDF-")) {
		return newPDFError(PDFErrorCorrupted, i18n.KeyToolPDFHelperInvalidHeader, filePath)
	}
	return nil
}

func getPDFPageCountWithPDFInfo(filePath string) (int, bool) {
	if _, err := exec.LookPath("pdfinfo"); err != nil {
		return 0, false
	}

	ctx, cancel := context.WithTimeout(context.Background(), pdfInfoTimeout)
	defer cancel()

	output, err := exec.CommandContext(ctx, "pdfinfo", filePath).CombinedOutput()
	if err != nil {
		return 0, false
	}
	match := pdfInfoPageCountPattern.FindStringSubmatch(string(output))
	if len(match) != 2 {
		return 0, false
	}
	count, err := strconv.Atoi(match[1])
	if err != nil {
		return 0, false
	}
	return count, true
}

func getPDFPageCountWithSwift(filePath string) (int, bool) {
	stdout, err := runSwiftPDFRenderer("count", filePath)
	if err != nil {
		return 0, false
	}
	count, err := strconv.Atoi(strings.TrimSpace(stdout))
	if err != nil {
		return 0, false
	}
	return count, true
}

func extractPDFPagesWithPDFToPPM(filePath, outputDir string, firstPage, lastPage int) error {
	args := []string{"-jpeg", "-r", "100"}
	if firstPage > 0 {
		args = append(args, "-f", strconv.Itoa(firstPage))
	}
	if lastPage > 0 && lastPage != math.MaxInt {
		args = append(args, "-l", strconv.Itoa(lastPage))
	}
	args = append(args, filePath, filepath.Join(outputDir, "page"))

	ctx, cancel := context.WithTimeout(context.Background(), pdfRenderTimeout)
	defer cancel()

	cmd := exec.CommandContext(ctx, "pdftoppm", args...)
	cmd.Env = pdfRendererEnvironment()
	output, err := cmd.CombinedOutput()
	if err == nil {
		return nil
	}
	stderr := strings.TrimSpace(string(output))
	if strings.Contains(strings.ToLower(stderr), "password") {
		return pdfErrorWithCause(PDFErrorPasswordProtected, i18n.KeyToolPDFHelperPasswordProtected, err)
	}
	if strings.Contains(strings.ToLower(stderr), "damaged") ||
		strings.Contains(strings.ToLower(stderr), "corrupt") ||
		strings.Contains(strings.ToLower(stderr), "invalid") {
		return pdfErrorWithCause(PDFErrorCorrupted, i18n.KeyToolPDFHelperCorrupted, err)
	}
	if stderr == "" {
		stderr = err.Error()
	}
	return pdfErrorWithCause(PDFErrorUnknown, i18n.KeyToolPDFHelperPDFToPPMFailed, err, stderr)
}

func pdfRendererEnvironment() []string {
	environment := os.Environ()
	if strings.TrimSpace(os.Getenv("FONTCONFIG_FILE")) != "" || strings.TrimSpace(os.Getenv("FONTCONFIG_PATH")) != "" {
		return environment
	}
	for _, candidate := range []string{
		"/opt/homebrew/etc/fonts/fonts.conf",
		"/usr/local/etc/fonts/fonts.conf",
		"/etc/fonts/fonts.conf",
	} {
		if info, err := os.Stat(candidate); err == nil && info.Mode().IsRegular() {
			return append(environment, "FONTCONFIG_FILE="+candidate)
		}
	}
	return environment
}

func extractPDFPagesWithSwift(filePath, outputDir string, firstPage, lastPage int) error {
	if runtime.GOOS != "darwin" {
		return fmt.Errorf(
			"pdftoppm is not installed. Install poppler-utils (e.g. `brew install poppler` or `apt-get install poppler-utils`) to enable PDF page rendering.",
		)
	}
	lastArg := "0"
	if lastPage > 0 && lastPage != math.MaxInt {
		lastArg = strconv.Itoa(lastPage)
	}
	if _, err := runSwiftPDFRenderer("extract", filePath, outputDir, strconv.Itoa(firstPage), lastArg); err != nil {
		return err
	}
	return nil
}

func ensureSwiftPDFRenderer() (string, error) {
	swiftPDFRendererOnce.Do(func() {
		if runtime.GOOS != "darwin" {
			swiftPDFRendererErr = fmt.Errorf(
				"pdftoppm is not installed. Install poppler-utils (e.g. `brew install poppler` or `apt-get install poppler-utils`) to enable PDF page rendering.",
			)
			return
		}
		if _, err := exec.LookPath("swift"); err != nil {
			swiftPDFRendererErr = fmt.Errorf(
				"pdftoppm is not installed. Install poppler-utils (e.g. `brew install poppler` or `apt-get install poppler-utils`) to enable PDF page rendering.",
			)
			return
		}

		file, err := os.CreateTemp("", "claude-pdf-renderer-*.swift")
		if err != nil {
			swiftPDFRendererErr = i18n.WrapError(i18n.KeyToolPDFCreateSwiftRendererScript, err)
			return
		}
		defer file.Close()

		if _, err := file.WriteString(swiftPDFRendererScript); err != nil {
			swiftPDFRendererErr = i18n.WrapError(i18n.KeyToolPDFWriteSwiftRendererScript, err)
			return
		}
		swiftPDFRendererPath = file.Name()
	})

	if swiftPDFRendererErr != nil {
		return "", swiftPDFRendererErr
	}
	return swiftPDFRendererPath, nil
}

func runSwiftPDFRenderer(args ...string) (string, error) {
	scriptPath, err := ensureSwiftPDFRenderer()
	if err != nil {
		return "", err
	}

	ctx, cancel := context.WithTimeout(context.Background(), pdfRenderTimeout)
	defer cancel()

	cmd := exec.CommandContext(ctx, "swift", append([]string{scriptPath}, args...)...)
	output, err := cmd.CombinedOutput()
	if err == nil {
		return strings.TrimSpace(string(output)), nil
	}

	message := strings.TrimSpace(string(output))
	if message == "" {
		message = err.Error()
	}
	return "", fmt.Errorf("%s", message)
}

func encodeBase64(data []byte) string {
	return base64.StdEncoding.EncodeToString(data)
}

const swiftPDFRendererScript = `import Foundation
import CoreGraphics
import ImageIO
import UniformTypeIdentifiers

enum RendererError: Error {
  case usage(String)
  case runtime(String)
}

func fail(_ error: Error) -> Never {
  let message: String
  if let rendererError = error as? RendererError {
    switch rendererError {
    case .usage(let text), .runtime(let text):
      message = text
    }
  } else {
    message = String(describing: error)
  }
  FileHandle.standardError.write(Data((message + "\n").utf8))
  exit(1)
}

func loadDocument(path: String) throws -> CGPDFDocument {
  guard let document = CGPDFDocument(URL(fileURLWithPath: path) as CFURL) else {
    throw RendererError.runtime("PDF file is corrupted or invalid.")
  }
  if document.isEncrypted {
    throw RendererError.runtime("PDF is password-protected. Please provide an unprotected version.")
  }
  return document
}

func writeJPEG(page: CGPDFPage, to url: URL, dpi: CGFloat = 100.0) throws {
  let box = page.getBoxRect(.mediaBox)
  let scale = max(dpi / 72.0, 0.1)
  let width = max(Int((box.width * scale).rounded(.up)), 1)
  let height = max(Int((box.height * scale).rounded(.up)), 1)

  let colorSpace = CGColorSpaceCreateDeviceRGB()
  guard let context = CGContext(
    data: nil,
    width: width,
    height: height,
    bitsPerComponent: 8,
    bytesPerRow: 0,
    space: colorSpace,
    bitmapInfo: CGImageAlphaInfo.noneSkipLast.rawValue
  ) else {
    throw RendererError.runtime("Failed to create PDF page rendering context.")
  }

  context.setFillColor(red: 1, green: 1, blue: 1, alpha: 1)
  context.fill(CGRect(x: 0, y: 0, width: CGFloat(width), height: CGFloat(height)))
  context.interpolationQuality = .high
  context.saveGState()
  context.translateBy(x: 0, y: CGFloat(height))
  context.scaleBy(x: scale, y: -scale)
  context.drawPDFPage(page)
  context.restoreGState()

  guard let image = context.makeImage() else {
    throw RendererError.runtime("Failed to render PDF page image.")
  }
  guard let destination = CGImageDestinationCreateWithURL(
    url as CFURL,
    UTType.jpeg.identifier as CFString,
    1,
    nil
  ) else {
    throw RendererError.runtime("Failed to create JPEG destination for PDF page image.")
  }

  let properties = [kCGImageDestinationLossyCompressionQuality: 0.8] as CFDictionary
  CGImageDestinationAddImage(destination, image, properties)
  if !CGImageDestinationFinalize(destination) {
    throw RendererError.runtime("Failed to write PDF page image.")
  }
}

do {
  let args = CommandLine.arguments
  guard args.count >= 3 else {
    throw RendererError.usage("usage: swift pdf_renderer.swift <count|extract> <pdf_path> [output_dir first_page last_page]")
  }

  let command = args[1]
  let pdfPath = args[2]
  let document = try loadDocument(path: pdfPath)

  switch command {
  case "count":
    print(document.numberOfPages)
  case "extract":
    guard args.count == 6 else {
      throw RendererError.usage("usage: swift pdf_renderer.swift extract <pdf_path> <output_dir> <first_page> <last_page_or_0>")
    }

    let outputDir = args[3]
    guard let firstPage = Int(args[4]), firstPage >= 1 else {
      throw RendererError.runtime("Invalid first page number.")
    }
    guard let requestedLastPage = Int(args[5]), requestedLastPage >= 0 else {
      throw RendererError.runtime("Invalid last page number.")
    }
    let lastPage = requestedLastPage == 0 ? document.numberOfPages : min(requestedLastPage, document.numberOfPages)
    if firstPage > document.numberOfPages || lastPage < firstPage {
      throw RendererError.runtime("Requested PDF page range is outside the document bounds.")
    }

    try FileManager.default.createDirectory(
      at: URL(fileURLWithPath: outputDir),
      withIntermediateDirectories: true,
      attributes: nil
    )

    var rendered = 0
    for pageNumber in firstPage...lastPage {
      guard let page = document.page(at: pageNumber) else {
        continue
      }
      let filename = String(format: "page-%02d.jpg", rendered + 1)
      let outputURL = URL(fileURLWithPath: outputDir).appendingPathComponent(filename)
      try writeJPEG(page: page, to: outputURL)
      rendered += 1
    }
    print(rendered)
  default:
    throw RendererError.usage("unsupported command: \(command)")
  }
} catch {
  fail(error)
}
`
